import { EntityDef } from './field.models';
import * as L from './value-lists';

/**
 * Schéma de la partie technique — GÉNÉRÉ depuis `audit_technique.xlsx`.
 *
 * `row` reproduit le numéro de ligne du tableau Excel : les champs partageant
 * la même valeur sont affichés côte à côte, comme le prescrit le classeur.
 * Les clés de stockage des robinets sont conservées à l'identique.
 *
 * `requirement` (obligatoire/recommande/facultatif) vient de la V3 du classeur
 * et pilote le niveau de remplissage choisi par l'auditeur, ainsi que la
 * validation à l'enregistrement pour les champs obligatoires.
 *
 * Régénérer avec `node tools/gen-schema.js` après modification du classeur.
 */
export const AUDIT_SCHEMA: EntityDef[] = [
  {
    key: "releve_compteur_general",
    route: "compteur-general",
    singular: "Compteur général",
    plural: "Compteur général",
    single: true,
    listColumns: [],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 7, requirement: "obligatoire" },
      { key: "ConditionDAcces", label: "Condition d'accès", kind: "text", row: 11, requirement: "facultatif" },
      { key: "Type", label: "Type", kind: "select", row: 14, options: L.TYPE_COMPTEUR, requirement: "obligatoire" },
      { key: "ClasseMetrologique", label: "Classe métrologique", kind: "select", row: 14, options: ["Classe A","Classe B","Classe C","Classe D","R40","R50","R63","R80","R100","R125","R160","R200","R250","R315","R400","R160","R200","R400","R500","R630","R800","Inconnue"], requirement: "obligatoire" },
      { key: "AnneeDePose", label: "Année de pose", kind: "number", row: 17, requirement: "facultatif" },
      { key: "ProprietaireDuCompteur", label: "Propriétaire du compteur", kind: "text", row: 17, requirement: "facultatif" },
      { key: "NombreDAbonnementEauPotable", label: "Nombre d'abonnement eau potable du bâtiment", kind: "number", row: 20, requirement: "facultatif" },
      { key: "Teletransmission", label: "Télétransmission", kind: "boolean", row: 23, requirement: "obligatoire" },
      { key: "PrecisionsTeletransmission", label: "Précisions télétransmission", kind: "text", row: 23, requirement: "facultatif" },
      { key: "DispositifRelieAuGtbGtc", label: "Dispositif relié au GTB/GTC ?", kind: "boolean", row: 26, requirement: "facultatif" },
      { key: "PresenceDeProtection", label: "Présence de protection (chocs, gel) ?", kind: "text", row: 29, requirement: "facultatif" },
      { key: "EtatGeneral", label: "Etat général*", kind: "select", row: 29, options: ["Bon","Moyen","Mauvais"], requirement: "obligatoire" },
      { key: "DysfonctionnementsObserves", label: "Dysfonctionnements observés", kind: "textarea", row: 32, wide: true, requirement: "obligatoire" },
      { key: "EnCasDImpossibiliteDe", label: "En cas d'impossibilité de relevé le compteur général - Indiquer les raisons", kind: "textarea", row: 35, wide: true, requirement: "facultatif" },
      { key: "PresenceDUnReducteurDe", label: "Présence d'un réducteur de pression à proximité ?", kind: "select", row: 43, options: ["Oui","Non","Si oui","afficher les champs dudessous. Si non","ne pas les afficher"], requirement: "obligatoire" },
      { key: "Reglage", label: "Réglage", kind: "text", row: 47 },
      { key: "PressionDeConsigneActuelle", label: "Pression de consigne actuelle", kind: "number", row: 47, unit: "bar", requirement: "recommande" },
      { key: "PressionAfficheeSiManometre", label: "Pression affichée si manomètre", kind: "number", row: 47, unit: "bar", requirement: "facultatif" },
      { key: "PlageDeReglageDeLa", label: "Plage de réglage de la pression", kind: "number", row: 50, unit: "bar", requirement: "facultatif" },
      { key: "DispositifRelieAuGtbGtcBis", label: "Dispositif relié au GTB/GTC ?", kind: "boolean", row: 50, requirement: "facultatif" },
      { key: "EtatGeneralBis", label: "Etat général*", kind: "select", row: 53, options: ["Bon","Moyen","Mauvais"], requirement: "obligatoire" },
      { key: "DysfonctionnementsObservesBis", label: "Dysfonctionnements observés", kind: "textarea", row: 56, wide: true, requirement: "obligatoire" },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 63, wide: true },
    ],
  },
  {
    key: "sous_compteurs",
    route: "sous-compteurs",
    singular: "Sous-compteur",
    plural: "Sous-compteurs",
    listColumns: ["Numero","Emplacement","AnneeDePose","Teletransmission"],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 8, requirement: "obligatoire" },
      { key: "UtilisationsDEauDesservisPar", label: "Utilisations d'eau desservis par le sous-compteur", kind: "text", row: 12 },
      { key: "ConditionDAcces", label: "Condition d'accès", kind: "text", row: 15, requirement: "facultatif" },
      { key: "Type", label: "Type", kind: "select", row: 18, options: L.TYPE_COMPTEUR, requirement: "obligatoire" },
      { key: "ClasseMetrologique", label: "Classe métrologique", kind: "select", row: 18, options: ["Classe A","Classe B","Classe C","Classe D","R40","R50","R63","R80","R100","R125","R160","R200","R250","R315","R400","R160","R200","R400","R500","R630","R800","Inconnue"], requirement: "obligatoire" },
      { key: "AnneeDePose", label: "Année de pose", kind: "number", row: 21, requirement: "recommande" },
      { key: "ProprietaireDuCompteur", label: "Propriétaire du compteur", kind: "text", row: 21, requirement: "facultatif" },
      { key: "Teletransmission", label: "Télétransmission", kind: "boolean", row: 24, requirement: "obligatoire" },
      { key: "PrecisionsTeletransmission", label: "Précisions télétransmission", kind: "text", row: 24, requirement: "facultatif" },
      { key: "DispoisitifRelieAuGtbGtc", label: "Dispoisitif relié au GTB/GTC ?", kind: "boolean", row: 27, requirement: "facultatif" },
      { key: "PresenceDeProtection", label: "Présence de protection (chocs, gel) ?", kind: "text", row: 30, requirement: "facultatif" },
      { key: "EtatGeneral", label: "Etat général*", kind: "select", row: 30, options: ["Bon","Moyen","Mauvais"], requirement: "obligatoire" },
      { key: "EnCasDImpossibiliteDe", label: "En cas d'impossibilité de relevé le compteur général - Indiquer les raisons", kind: "textarea", row: 33, wide: true, requirement: "facultatif" },
      { key: "DysfonctionnementsObserves", label: "Dysfonctionnements observés", kind: "textarea", row: 36, wide: true, requirement: "obligatoire" },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 39, wide: true },
    ],
  },
  {
    key: "surpresseurs",
    route: "surpresseurs",
    singular: "Surpresseur",
    plural: "Surpresseurs",
    listColumns: ["Numero","Emplacement","AnneeDePose"],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 8 },
      { key: "ConditionDAcces", label: "Condition d'accès", kind: "text", row: 12 },
      { key: "Marque", label: "Marque", kind: "text", row: 15 },
      { key: "Modele", label: "Modèle", kind: "text", row: 15 },
      { key: "Type", label: "Type", kind: "text", row: 18 },
      { key: "DiametreNominal", label: "Diamètre Nominal", kind: "number", row: 18, unit: "mm" },
      { key: "AnneeDePose", label: "Année de pose", kind: "number", row: 21 },
      { key: "PressionAfficheeSiManometre", label: "Pression affichée si manomètre", kind: "number", row: 21, unit: "bar" },
      { key: "PressionDeConsigneActuelle", label: "Pression de consigne actuelle", kind: "number", row: 24, unit: "bar" },
      { key: "PlageDeReglageDeLa", label: "Plage de réglage de la pression", kind: "number", row: 24, unit: "bar" },
      { key: "EtatGeneral", label: "Etat général", kind: "select", row: 27, options: ["Bon","Moyen","Mauvais"] },
      { key: "DateDerniereMaintenance", label: "Date dernière maintenance", kind: "text", row: 27 },
      { key: "OrganesDeReseauAProximite", label: "Organes de réseau à proximité", kind: "text", row: 30 },
      { key: "DysfonctionnementsObserves", label: "Dysfonctionnements observés", kind: "textarea", row: 33, wide: true },
      { key: "DispositifRelieAuGtbGtc", label: "Dispositif relié au GTB/GTC ?", kind: "boolean", row: 36 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 39, wide: true },
    ],
  },
  {
    key: "reseaux_eau_chaude_sanitaire",
    route: "reseaux-ecs",
    singular: "Réseau ECS",
    plural: "Réseaux ECS",
    listColumns: ["Numero","MateriauPrincipalDesCanalisations","DiametreDesGaines","Bouclage"],
    fields: [
      { key: "ReseauDeDistributionDEau", label: "Réseau de distribution d'Eau Chaude Sanitaire", kind: "text", row: 6 },
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 9, requirement: "obligatoire" },
      { key: "AnneeDInstallation", label: "Année d'installation", kind: "number", row: 13, requirement: "facultatif" },
      { key: "MateriauPrincipalDesCanalisations", label: "Matériau principal des canalisations", kind: "select", row: 16, options: ["Cuivre","Multicouche","PER","PEHD","PE","pvc sous pression","acier galvanisé","fonte"], requirement: "obligatoire" },
      { key: "DiametreDesGainesAuDepart", label: "Diamètre des gaines (mm) au départ du générateur ECS", kind: "number", row: 19, unit: "mm", requirement: "obligatoire" },
      { key: "LongueurTotaleDuReseau", label: "Longueur totale du réseau (si connue)", kind: "text", row: 22, requirement: "facultatif" },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 25, wide: true },
      { key: "CalorifugeageDesCanalisations", label: "Calorifugeage des canalisations", kind: "select", row: 29, options: ["oui","non","ne sait pas"], requirement: "recommande" },
      { key: "EpaisseurDeLIsolant", label: "Epaisseur de l'isolant", kind: "number", row: 32, unit: "mm", requirement: "facultatif" },
      { key: "MateriauxDeLIsolant", label: "Matériaux de l'isolant", kind: "select", row: 35, options: ["laine de verre","laine de roche","papier et platre","polyruéthane","Mousse synthétique (armaflex,PE…)"], requirement: "facultatif" },
      { key: "ContinuiteDeLIsolation", label: "Continuité de l'isolation", kind: "select", row: 38, options: ["oui","non","ne sait pas"], requirement: "facultatif" },
      { key: "EtatDeLIsolant", label: "Etat de l'isolant*", kind: "select", row: 41, options: ["Bon","Moyen","Mauvais"], requirement: "recommande" },
      { key: "RemarquesBis", label: "Remarques", kind: "textarea", row: 44, wide: true },
      { key: "Bouclage", label: "Bouclage", kind: "select", row: 51, options: ["oui","non","ne sait pas"], requirement: "obligatoire" },
      { key: "DebitRegleSurLaPompe", label: "Débit réglé sur la pompe/circulateur", kind: "number", row: 54, unit: "l/s", requirement: "recommande" },
      { key: "TemperatureAfficheeDuDepartEcs", label: "Température affichée du départ ECS", kind: "number", row: 57, unit: "°C", requirement: "recommande" },
      { key: "TemperatureAfficheeDuRetourDe", label: "Température affichée du retour de boucle", kind: "number", row: 60, unit: "°C", requirement: "recommande" },
      { key: "EcartDeTemperatureEntreLe", label: "Ecart de température entre le départ et le retour", kind: "number", row: 63, unit: "°C", requirement: "recommande" },
      { key: "MarqueEtModeleDuCirculateur", label: "Marque et modèle du circulateur", kind: "text", row: 67, requirement: "facultatif" },
      { key: "ModeDeFonctionnementDuCirculateur", label: "Mode de fonctionnement du circulateur", kind: "select", row: 70, options: ["continu","horloge programmable","piloté par la température","aquastat","GTB","GTC"], requirement: "recommande" },
      { key: "VariationDeVitesseDuCirculateur", label: "Variation de vitesse du circulateur possible", kind: "boolean", row: 73, requirement: "recommande" },
      { key: "DegradationDysfonctionnementsObserves", label: "Dégradation / dysfonctionnements observés", kind: "textarea", row: 76, wide: true, requirement: "recommande" },
      { key: "RemarquesBisBis", label: "Remarques", kind: "textarea", row: 79, wide: true },
      { key: "PresenceDUneOuPlusieurs", label: "Présence d'une ou plusieurs vanne(s) thermostatique", kind: "select", row: 84, options: ["manuelle","motorisée","non","ne sait pas"], requirement: "facultatif" },
      { key: "PresenceDUnClapetAnti", label: "Présence d'un clapet anti-retour", kind: "select", row: 87, options: ["oui","non","ne sait pas"], requirement: "facultatif" },
      { key: "PresenceDUnVaseD", label: "Présence d'un vase d'expansion", kind: "select", row: 90, options: ["oui","non","ne sait pas"], requirement: "facultatif" },
      { key: "RemarquesBisBisBis", label: "Remarques", kind: "textarea", row: 97, wide: true },
      { key: "PresenceDeBrasMortConnus", label: "Présence de bras mort connus", kind: "select", row: 101, options: ["oui","non","ne sait pas"], requirement: "recommande" },
      { key: "Precisions", label: "Précisions", kind: "text", row: 104, requirement: "facultatif" },
      { key: "ProtocolePourLeRisqueLegionnelle", label: "Protocole pour le risque légionnelle déjà mis en place ?", kind: "select", row: 108, options: ["oui","non","ne sait pas"], requirement: "obligatoire" },
      { key: "PresenceDUnePurgeAutomatique", label: "Présence d'une purge automatique", kind: "select", row: 111, options: ["oui","non","ne sait pas"], requirement: "recommande" },
      { key: "PresenceDUnTraitementComplementaire", label: "Présence d'un traitement complémentaire contre la légionnelle ?", kind: "text", row: 114, requirement: "recommande" },
      { key: "RemarquesBisBisBisBis", label: "Remarques", kind: "textarea", row: 117, wide: true },
    ],
  },
  {
    key: "production_stockage_ecs",
    route: "production-stockage-ecs",
    singular: "Production / Stockage ECS",
    plural: "Production / Stockage ECS",
    listColumns: ["Numero","TypeDeSystemeDeProduction","SystemesDeProduction"],
    fields: [
      { key: "ProductionStockageDEauChaude", label: "Production / Stockage d' Eau Chaude Sanitaire", kind: "text", row: 6 },
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 9, requirement: "obligatoire" },
      { key: "ChauffageDuLocalOuSe", label: "Chauffage du local où se situe le stockage", kind: "text", row: 13, requirement: "recommande" },
      { key: "NumeroDeReseauEcsAssocie", label: "Numéro de réseau ECS associé", kind: "select", row: 16, options: ["correspondant aux champs \"numéro de réseau ECS\" précedemment remplis"], requirement: "obligatoire" },
      { key: "TypeDeSystemeDeProduction", label: "Type de système de production/stockage d'ECS", kind: "text", row: 19, requirement: "obligatoire" },
      { key: "ModeDeProductionStockageD", label: "Mode de production/stockage d'ECS", kind: "text", row: 22, requirement: "obligatoire" },
      { key: "Type", label: "Type", kind: "text", row: 27, requirement: "obligatoire" },
      { key: "SystemesDeProduction", label: "Systèmes de production", kind: "select", row: 30, options: ["Chauffe-eau gaz instantané","Accumulateur gaz","Chaudière","Ballon électrique","Chauffe-eau électrique","Chauffe-eau solaire thermique","Solaire photovoltaïque","Système solaire combiné chauffage + ECS","Chauffe-eau thermodynamique individuel (ie PAC)","PAC (indiviuuelle ou collective)","Module thermique d'appartements (MTA)","Kit robinetterie avec module chaufffant","Autre (préciser dans remarques)","Ne sait pas"], requirement: "obligatoire" },
      { key: "Combustible", label: "Combustible", kind: "select", row: 33, options: ["gaz","fioul","bois","biomasse","réseau de chaleur urbain","ne sait pas","autre"], requirement: "obligatoire" },
      { key: "MarqueEtModeleDuGenerateur", label: "Marque et modèle du générateur", kind: "text", row: 36, requirement: "facultatif" },
      { key: "RegulationPilotageDeLaProduction", label: "Régulation / pilotage de la production", kind: "text", row: 39, requirement: "recommande" },
      { key: "EtatApparentDuGenerateur", label: "Etat apparent du générateur*", kind: "select", row: 42, options: ["Bon","Moyen","Mauvais"], requirement: "recommande" },
      { key: "DegradationDysfonctionnementsObserves", label: "Dégradation / dysfonctionnements observés", kind: "textarea", row: 45, wide: true, requirement: "recommande" },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 48, wide: true },
      { key: "NombreDeBallonDeStockage", label: "Nombre de ballon de stockage", kind: "number", row: 56, requirement: "obligatoire" },
      { key: "VolumeTotalDeStockage", label: "Volume total de stockage (L)", kind: "number", row: 59, unit: "L", requirement: "obligatoire" },
      { key: "MontageDesBallons", label: "Montage des ballons", kind: "text", row: 62, requirement: "facultatif" },
      { key: "EtatApparentDuBallons", label: "Etat apparent du (des) ballons*", kind: "text", row: 65, requirement: "recommande" },
      { key: "DegradationDysfonctionnementsObservesBis", label: "Dégradation / dysfonctionnements observés", kind: "textarea", row: 68, wide: true, requirement: "recommande" },
      { key: "IsolationDuBallons", label: "Isolation du (des) ballons", kind: "text", row: 76, requirement: "obligatoire" },
      { key: "ContinuiteDeLIsolantSur", label: "Continuité de l'isolant sur tout le (les) ballons", kind: "select", row: 79, options: ["oui","non","ne sait pas"], requirement: "facultatif" },
      { key: "EtatDeLIsolant", label: "Etat de l'isolant*", kind: "select", row: 82, options: ["bon","moyen","mauvais"], requirement: "recommande" },
      { key: "RemarquesBis", label: "Remarques", kind: "textarea", row: 85, wide: true },
      { key: "TemperatureAfficheeSurLeBallon", label: "Température affichée sur le ballon", kind: "number", row: 93, unit: "°C", requirement: "obligatoire" },
      { key: "PresenceDUneSoupapeDe", label: "Présence d'une soupape de sécurité", kind: "select", row: 98, options: ["oui","non","ne sait pas"], requirement: "facultatif" },
      { key: "PresenceDUnVaseD", label: "Présence d'un vase d'expansion entre la soupape de sécurité et le stockage", kind: "select", row: 101, options: ["oui","non","ne sait pas"], requirement: "facultatif" },
      { key: "DegradationDysfonctionnementsObservesBisBis", label: "Dégradation / dysfonctionnements observés", kind: "textarea", row: 104, wide: true, requirement: "recommande" },
      { key: "RemarquesBisBis", label: "Remarques", kind: "textarea", row: 107, wide: true },
    ],
  },
  {
    key: "robinets",
    route: "robinets",
    singular: "Robinet",
    plural: "Robinets",
    listColumns: ["Numero","Emplacement","Type","Debit"],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 8, requirement: "obligatoire" },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 11, requirement: "recommande" },
      { key: "Utilisations", label: "Utilisations", kind: "text", row: 15 },
      { key: "Utilisation1", label: "Utilisation 1", kind: "select", row: 15, options: ["Evier","Lave-main","Fontaine","Lavabo","Ménage/lavage du sol","Lavage poubelle","Lavage matériel (pinceau, ...)","Table à langer","Poste de plonge","Poste de rinçage","Robinet extérieur","Arrosage","Lavage de véhicule","Chaufferie/technique","Autre"], requirement: "obligatoire" },
      { key: "Utilisation2", label: "Utilisation 2", kind: "select", row: 15, options: ["Evier","Lave-main","Fontaine","Lavabo","Ménage/lavage du sol","Lavage poubelle","Table à langer","Poste de plonge","Poste de rinçage","Robinet extérieur","Arrosage","Lavage de véhicule","Chaufferie/technique","Autre"], requirement: "recommande" },
      { key: "Utilisation3", label: "Utilisation 3", kind: "select", row: 15, options: ["Evier cuisine","Lave-main","Fontaine","Lavabo","Ménage/lavage du sol","Lavage poubelle","Lavage matériel (pinceau, ...)","Table à langer","Poste de plonge","Poste de rinçage","Robinet extérieur","Arrosage","Lavage de véhicule","Chaufferie/technique","Autre"], requirement: "facultatif" },
      { key: "Usagers", label: "Usagers", kind: "text", row: 18, requirement: "obligatoire" },
      { key: "NombreDUtilisationSemaine", label: "Nombre d'utilisation/semaine", kind: "number", row: 18, requirement: "facultatif" },
      { key: "NombreDEquipementsIdentiques", label: "Nombre d'équipements identiques", kind: "number", row: 21, requirement: "obligatoire" },
      { key: "NumeroReseauEcsDAppartenance", label: "Numéro réseau ECS d'appartenance", kind: "entity-ref", row: 21, refTo: "reseaux_eau_chaude_sanitaire", requirement: "obligatoire" },
      { key: "TypeDeRobinets", label: "Type de robinets", kind: "select", row: 24, options: ["Simple EF","Simple ECS","Mélangeur","Mitigeur classique","Mitigeur thermostatique"], requirement: "obligatoire" },
      { key: "CommandeDuRobinet", label: "Commande du robinet", kind: "select", row: 24, options: ["manuelle","fémorale","à pédale","à détection"], requirement: "obligatoire" },
      { key: "Temporisation", label: "Temporisation", kind: "select", row: 27, options: L.TEMPORISATION, requirement: "obligatoire" },
      { key: "TempsDeLaTemporisation", label: "Temps de la temporisation", kind: "number", row: 27, unit: "s", requirement: "recommande" },
      { key: "DiametreNominalDeLAlimentation", label: "Diamètre Nominal de l'alimentation", kind: "number", row: 30, unit: "mm", requirement: "facultatif" },
      { key: "MateriauDuTuyauDAlimentation", label: "Matériau du tuyau d'alimentation", kind: "select", row: 30, options: ["Cuivre","Multicouche","PER","PEHD","PE","PVC pression","inconnu"], requirement: "facultatif" },
      { key: "PresenceDUnLimiteurDe", label: "Présence d'un limiteur de débit", kind: "select", row: 33, options: ["Oui","Non"], requirement: "recommande" },
      { key: "Particularite", label: "Particularité", kind: "text", row: 33, requirement: "recommande" },
      { key: "InformationsSurLeBecDu", label: "Informations sur le bec du robinet", kind: "text", row: 36, requirement: "facultatif" },
      { key: "Temps", label: "Temps", kind: "number", row: 40, unit: "s" },
      { key: "Volume", label: "Volume", kind: "number", row: 40, unit: "L" },
      { key: "CalculDebit", label: "Calcul débit", kind: "number", row: 40, unit: "L/min" },
      { key: "MesureDirecteDebitBol", label: "Mesure directe débit (L/min) - bol", kind: "number", row: 40, unit: "L/min" },
      { key: "TemperatureMaxEcs", label: "Température max ECS", kind: "number", row: 45, unit: "°C", requirement: "facultatif" },
      { key: "TempsDObtentionEcs", label: "Temps d'obtention (s) ECS", kind: "number", row: 45, unit: "s", requirement: "facultatif" },
      { key: "AnneeDePose", label: "Année de pose", kind: "number", row: 48, requirement: "facultatif" },
      { key: "DateDerniereMaintenance", label: "Date dernière maintenance", kind: "text", row: 48, requirement: "facultatif" },
      { key: "EtatGeneral", label: "Etat général*", kind: "select", row: 51, options: ["Bon","Moyen","Mauvais"], requirement: "recommande" },
      { key: "DysfonctionnementsObserves", label: "Dysfonctionnements observés", kind: "textarea", row: 54, wide: true, requirement: "recommande" },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 57, wide: true },
    ],
  },
  {
    key: "douches_baignoires",
    route: "douches-baignoires",
    singular: "Douche / Baignoire",
    plural: "Douches et baignoires",
    listColumns: ["Numero","TypeDEquipement","Emplacement"],
    fields: [
      { key: "TypeDEquipement", label: "Type d'équipement", kind: "select", row: 8, options: ["douche ou baignoire","Affiche ensuite la partie","\"Douche\" ou \"Baignoire\""], requirement: "obligatoire" },
      { key: "NombreDEquipementsIdentiques", label: "Nombre d'équipements identiques", kind: "number", row: 11, requirement: "obligatoire" },
      { key: "NumeroReseauEcsDAppartenance", label: "Numéro réseau ECS d'appartenance", kind: "entity-ref", row: 11, refTo: "reseaux_eau_chaude_sanitaire", requirement: "obligatoire" },
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 14, requirement: "obligatoire" },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 17, requirement: "recommande" },
      { key: "Usagers", label: "Usagers", kind: "text", row: 21, requirement: "recommande" },
      { key: "NombreDUtilisationSemaine", label: "Nombre d'utilisation/semaine", kind: "number", row: 21, requirement: "facultatif" },
      { key: "TypeDeSol", label: "Type de sol", kind: "select", row: 25, options: ["receveur","à l'italienne carrellée","à l'italienne pierre naturelle","chape béton étanche"], requirement: "facultatif" },
      { key: "AdapteePmr", label: "Adaptée PMR ?", kind: "select", row: 25, options: ["Oui","Non"], requirement: "recommande" },
      { key: "TypeDEmetteur", label: "Type d'emetteur", kind: "select", row: 28, options: ["tête de douche","ciel de pluie","pommeau","colonne hydromassante","cascade","Autre"], requirement: "obligatoire" },
      { key: "JetsDeLEmetteur", label: "Jets de l'émetteur", kind: "select", row: 28, options: ["aucune","pluie laminaire","aéré","brumisé","pulsé/massage","concentré/puissant","multi-jets"], requirement: "facultatif" },
      { key: "PresenceDUnLimiteurDe", label: "Présence d'un limiteur de débit", kind: "boolean", row: 41, requirement: "obligatoire" },
      { key: "ParticularitesDeLaDouche", label: "Particularités de la douche", kind: "text", row: 41, requirement: "facultatif" },
      { key: "Temps", label: "Temps", kind: "number", row: 45, unit: "s" },
      { key: "Volume", label: "Volume", kind: "number", row: 45, unit: "L" },
      { key: "Debit", label: "Débit", kind: "number", row: 45, unit: "L/min" },
      { key: "MesureDirecteDebitBol", label: "Mesure directe débit (L/min) - bol", kind: "number", row: 45, unit: "L/min" },
      { key: "TemperatureMaxEcs", label: "Température max ECS", kind: "number", row: 50, unit: "°C", requirement: "recommande" },
      { key: "TempsDObtentionEcs", label: "Temps d'obtention (s) ECS", kind: "number", row: 50, unit: "s", requirement: "recommande" },
      { key: "EtatGeneral", label: "Etat général", kind: "select", row: 53, options: ["Bon","Moyen","Mauvais"], requirement: "recommande" },
      { key: "DateDerniereMaintenance", label: "Date dernière maintenance", kind: "text", row: 53, requirement: "facultatif" },
      { key: "DysfonctionnementsObserves", label: "Dysfonctionnements observés", kind: "textarea", row: 56, wide: true, requirement: "recommande" },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 59, wide: true },
      { key: "MauvaisEtat", label: "Mauvais état", kind: "text", row: 64 },
      { key: "EquipementAncienFuitePermanenteEntartrage", label: "équipement ancien, fuite permanente, entartrage important, flexible abîmé, jets irréguliers en permanence, mauvais état des joints du receveur", kind: "text", row: 64 },
      { key: "TypeDeBaignoire", label: "Type de baignoire", kind: "select", row: 66, options: ["sur pied","autoportante","encastrée","sabot","îlot","autre"], requirement: "facultatif" },
      { key: "AdapteePmrBis", label: "Adaptée PMR ?", kind: "select", row: 66, options: ["Oui","Non"], requirement: "recommande" },
      { key: "BaignoireIndiquerSesDimensions", label: "Baignoire - Indiquer ses dimensions", kind: "number", row: 69, unit: "cm" },
      { key: "BaignoireIndiquerSonVolume", label: "Baignoire - Indiquer son volume", kind: "number", row: 69, unit: "L" },
      { key: "TypeDEmetteurBis", label: "Type d'émetteur", kind: "select", row: 72, options: ["Robinet seul","Robinet + pommeau","Pommeau seul","Robinet + colonne de douche","Robinet + buses hydromassante"], requirement: "obligatoire" },
      { key: "JetsDeLEmetteurBis", label: "Jets de l'émetteur", kind: "select", row: 72, options: ["aucune","pluie laminaire","aéré","brumisé","pulsé/massage","concentré/puissant","multi-jets"], requirement: "facultatif" },
      { key: "PresenceDUnLimiteurDeBis", label: "Présence d'un limiteur de débit", kind: "boolean", row: 80, requirement: "obligatoire" },
      { key: "ParticularitesDeLaBaignoire", label: "Particularités de la baignoire", kind: "text", row: 80, requirement: "facultatif" },
      { key: "TempsBis", label: "Temps", kind: "number", row: 84, unit: "s" },
      { key: "VolumeBis", label: "Volume", kind: "number", row: 84, unit: "L" },
      { key: "CalculDebit", label: "Calcul débit", kind: "number", row: 84, unit: "L/min" },
      { key: "MesureDirecteDebitBolBis", label: "Mesure directe débit (L/min) - bol", kind: "number", row: 84, unit: "L/min" },
      { key: "TemperatureMaxEcsBis", label: "Température max ECS", kind: "number", row: 89, unit: "°C", requirement: "recommande" },
      { key: "TempsDObtentionEcsBis", label: "Temps d'obtention (s) ECS", kind: "number", row: 89, unit: "s", requirement: "recommande" },
      { key: "EtatGeneralBis", label: "Etat général*", kind: "select", row: 92, options: ["Bon","Moyen","Mauvais"], requirement: "recommande" },
      { key: "DateDerniereMaintenanceBis", label: "Date dernière maintenance", kind: "text", row: 92, requirement: "facultatif" },
      { key: "DysfonctionnementsObservesBis", label: "Dysfonctionnements observés", kind: "textarea", row: 95, wide: true, requirement: "recommande" },
      { key: "RemarquesBis", label: "Remarques", kind: "textarea", row: 98, wide: true },
      { key: "MauvaisEtatBis", label: "Mauvais état", kind: "text", row: 103 },
      { key: "EquipementAncienFuitePermanenteEntartrageBis", label: "équipement ancien, fuite permanente, entartrage important, flexible abîmé, jets irréguliers en permanence, mauvais état des joints du receveur", kind: "text", row: 103 },
      { key: "Type", label: "Type", kind: "select", row: 105, options: ["Simple EF","Simple ECS","Mélangeur","Mitigeur classique","Mitigeur thermostatique"], requirement: "obligatoire" },
      { key: "CommandeDuRobinet", label: "Commande du robinet", kind: "select", row: 105, options: ["manuelle","à détection de présence","à effleurement","à détection RFID"], requirement: "obligatoire" },
      { key: "Temporisation", label: "Temporisation", kind: "select", row: 108, options: L.TEMPORISATION, requirement: "obligatoire" },
      { key: "TempsDeLaTemporisation", label: "Temps de la temporisation", kind: "number", row: 108, unit: "s", requirement: "recommande" },
      { key: "ParticularitesDuRobinet", label: "Particularités du robinet", kind: "text", row: 111, requirement: "facultatif" },
      { key: "DiametreNominalDeLAlimentation", label: "Diamètre Nominal de l'alimentation", kind: "number", row: 114, unit: "mm", requirement: "recommande" },
      { key: "MateriauDuTuyauDAlimentation", label: "Matériau du tuyau d'alimentation", kind: "select", row: 114, options: ["Cuivre","Multicouche","PER","PEHD","PE","PVC pression","inconnu"], requirement: "recommande" },
      { key: "EtatGeneralBisBis", label: "Etat général*", kind: "select", row: 117, options: ["Bon","Moyen","Mauvais"], requirement: "recommande" },
      { key: "DateDerniereMaintenanceBisBis", label: "Date dernière maintenance", kind: "text", row: 117, requirement: "facultatif" },
      { key: "DysfonctionnementsObservesBisBis", label: "Dysfonctionnements observés", kind: "textarea", row: 120, wide: true, requirement: "recommande" },
      { key: "RemarquesBisBis", label: "Remarques", kind: "textarea", row: 123, wide: true },
    ],
  },
  {
    key: "wc",
    route: "wc",
    singular: "WC",
    plural: "WC",
    listColumns: ["Numero","TypeDeToiletteOuUrinoir","Emplacement","NombreDEquipementsIdentiques"],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 8, requirement: "obligatoire" },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 11, requirement: "facultatif" },
      { key: "Utilisateurs", label: "Utilisateurs", kind: "select", row: 15, options: ["(plusieurs réponses possibles)","Public extérieur","Personnel","Autres adultes","Enfants","Adolescents","Personnes âgées","PMR"], requirement: "obligatoire" },
      { key: "MixteOuGenre", label: "Mixte ou genré ?", kind: "select", row: 15, options: ["Homme","Femme","Mixte"], requirement: "obligatoire" },
      { key: "TypeDeToiletteOuUrinoir", label: "Type de toilette ou urinoir", kind: "text", row: 18, requirement: "obligatoire" },
      { key: "NombreDEquipementsIdentiques", label: "Nombre d'équipements identiques", kind: "number", row: 18, requirement: "obligatoire" },
      { key: "TypeDeChasse", label: "Type de chasse", kind: "text", row: 33, requirement: "facultatif" },
      { key: "MarqueOuModeleSiConnu", label: "Marque ou modèle si connu", kind: "text", row: 33, requirement: "facultatif" },
      { key: "CommandeDeLaChasse", label: "Commande de la chasse", kind: "select", row: 36, options: L.COMMANDE_CHASSE, requirement: "obligatoire" },
      { key: "OrigineDeLEau", label: "Origine de l'eau", kind: "select", row: 36, options: ["Eau potable","Eau de pluie","Eau forage brute","Eau grise"], requirement: "facultatif" },
      { key: "VolumeChasseEstimeOuConnu", label: "Volume chasse estimé ou connu", kind: "select", row: 39, options: ["<3","2/4","3/6","6/9","6","9",">9","Inconnu","Non concerné"] },
      { key: "VolumeChasseSiMesure", label: "Volume chasse si mesuré", kind: "number", row: 39 },
      { key: "TesteDeLaFeuilleDe", label: "Teste de la feuille de papier toilette dans la cuvette", kind: "select", row: 42, options: ["feuille mouillée - fuite observée","feuille semi-mouillée - fuite suspectée","feuille sèche - pas de fuite"] },
      { key: "DateDernierReglageChasseD", label: "Date dernier réglage chasse d'eau", kind: "text", row: 42, requirement: "facultatif" },
      { key: "Ventilation", label: "Ventilation", kind: "select", row: 45, options: ["pas de ventilation","en continu","intermittente","à détection","indépendante du reste du bâtiment"] },
      { key: "TestDeLaFeuilleDe", label: "Test de la feuille de papier sur la bouche d'extraction", kind: "select", row: 45, options: ["Feuille aspirée","Feuille repoussée","Rien ne se passe"] },
      { key: "EstCeQueLesToilettes", label: "Est-ce que les toilettes ont un mur qui donne sur l'extérieur (sur la parcelle du bâtiment uniquement) ?", kind: "text", row: 48, requirement: "recommande" },
      { key: "DisponibiliteDUnLocalA", label: "Disponibilité d'un local à proximité pour accueillir un composteur", kind: "select", row: 48, options: ["non","oui à côté","derrière un des murs","oui à l'aplomb aux étages inférieurs"], requirement: "recommande" },
      { key: "EtatGeneral", label: "Etat général", kind: "text", row: 51, requirement: "recommande" },
      { key: "DateDerniereMaintenance", label: "Date dernière maintenance", kind: "text", row: 51, requirement: "facultatif" },
      { key: "DysfonctionnementsObserves", label: "Dysfonctionnements observés", kind: "select", row: 54, options: ["Fuite de la chasse","Traces de fuite","Bouton chasse cassé ou bloqué","Bruits de la chasse en continu","Entartrage","Odeurs","WC bouché","Lunette cassée"], requirement: "recommande" },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 57, wide: true },
    ],
  },
  {
    key: "appareils_lavage",
    route: "appareils-lavage",
    singular: "Appareil de lavage",
    plural: "Appareils de lavage",
    listColumns: ["Numero","Emplacement","Type"],
    fields: [
      { key: "Type", label: "Type", kind: "select", row: 8, options: ["lave linge","lave vaisselle","autolaveuse","lavage du sol manuel"] },
      { key: "NombreDEquipementIdentique", label: "Nombre d'équipement identique", kind: "number", row: 8 },
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 11, requirement: "obligatoire" },
      { key: "PrecisionsEmplacement", label: "Précisions emplacement", kind: "text", row: 14 },
      { key: "Utilisation", label: "Utilisation", kind: "text", row: 19 },
      { key: "Utilisations", label: "Utilisations", kind: "select", row: 19, options: ["domestique","collective","professionnelle"], requirement: "obligatoire" },
      { key: "NbDUtilisationSemaine", label: "Nb d'utilisation / semaine", kind: "number", row: 19, requirement: "recommande" },
      { key: "TauxDeRemplissage", label: "Taux de remplissage", kind: "select", row: 22, options: ["peu rempli","semi-rempli","plein"], requirement: "facultatif" },
      { key: "TemperatureDeLavageLaPlus", label: "Température de lavage la plus fréquente", kind: "text", row: 22, requirement: "facultatif" },
      { key: "ListerLesProgrammesLesPlus", label: "Lister les programmes les plus utilisés", kind: "text", row: 25, requirement: "facultatif" },
      { key: "Capacite", label: "Capacité", kind: "number", row: 28, unit: "kg", requirement: "recommande" },
      { key: "ClasseEnergetique", label: "Classe énergétique", kind: "select", row: 28, options: ["A","B","C","D","E","F","G"], requirement: "recommande" },
      { key: "MarqueEtModele", label: "Marque et modèle", kind: "text", row: 31, requirement: "facultatif" },
      { key: "TypeDAlimentationEnEau", label: "Type d'alimentation en eau", kind: "select", row: 31, options: ["EF seul","EF + ECS","Eau de pluie"], requirement: "recommande" },
      { key: "DateDInstallation", label: "Date d'installation", kind: "text", row: 34, requirement: "facultatif" },
      { key: "TypeDeTextilesLaves", label: "Type de textiles lavés", kind: "select", row: 34, options: ["à cocher (plusieurs réponses possibles) :","vêtements quotidien mixte (coton, mélange, soie, laine, synthétique)","vêtements de sport (synthétique)","vêtements laine","textile hébergement (literie, peignoirs, serviette)","textile ameublement (rideaux, housse)","textile de restauration (nappes, torchons, serviettes de table)","textile médical (tenues, draps)","textile de nettoyage (franges, chiffons, microfibres)","vêtements professionnels très sales","textiles à risques infectieux"], requirement: "recommande" },
      { key: "EtatVisuelDeLaMachine", label: "Etat visuel de la machine*", kind: "text", row: 37, requirement: "recommande" },
      { key: "DysfonctionnementsObserves", label: "Dysfonctionnements observés", kind: "textarea", row: 37, wide: true, requirement: "recommande" },
      { key: "ProceduresDEntretienRealiseesEt", label: "Procédures d'entretien réalisées (lavage à vide à 65°C, vinaigre blanc, etc.) et fréquence", kind: "text", row: 40, requirement: "facultatif" },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 43, wide: true },
      { key: "UtilisationsBis", label: "Utilisations", kind: "text", row: 50 },
      { key: "UtilisationsBisBis", label: "Utilisations", kind: "select", row: 50, options: ["domestique","collectif","professionnel"], requirement: "obligatoire" },
      { key: "NbDUtilisationSemaineBis", label: "Nb d'utilisation / semaine", kind: "number", row: 50, requirement: "recommande" },
      { key: "TauxDeRemplissageBis", label: "Taux de remplissage", kind: "text", row: 53, requirement: "facultatif" },
      { key: "TemperatureDeLavageLaPlusBis", label: "Température de lavage la plus fréquente", kind: "text", row: 53, requirement: "facultatif" },
      { key: "ListerLesProgrammesLesPlusBis", label: "Lister les programmes les plus utilisés", kind: "text", row: 56, requirement: "facultatif" },
      { key: "CapaciteBis", label: "Capacité", kind: "text", row: 59, requirement: "recommande" },
      { key: "TypeDeChargement", label: "Type de chargement", kind: "select", row: 59, options: ["frontal","à capot","à avancement automatique","à convoyeur/tunnel"], requirement: "recommande" },
      { key: "MarqueEtModeleBis", label: "Marque et modèle", kind: "text", row: 62, requirement: "facultatif" },
      { key: "TypeDAlimentationEnEauBis", label: "Type d'alimentation en eau", kind: "select", row: 62, options: ["EF seul","ECS seul","EF + ECS"], requirement: "recommande" },
      { key: "DateDInstallationBis", label: "Date d'installation", kind: "text", row: 65, requirement: "facultatif" },
      { key: "ClasseEnergetiqueBis", label: "Classe énergétique", kind: "text", row: 65, requirement: "recommande" },
      { key: "EtatVisuelDeLaMachineBis", label: "Etat visuel de la machine*", kind: "text", row: 68, requirement: "recommande" },
      { key: "DysfonctionnementsObservesBis", label: "Dysfonctionnements observés", kind: "textarea", row: 68, wide: true, requirement: "recommande" },
      { key: "ProceduresDEntretienRealiseesEtBis", label: "Procédures d'entretien réalisées (lavage à vide à 65°C, vinaigre blanc, etc.) et fréquence", kind: "text", row: 72, requirement: "facultatif" },
      { key: "RemarquesBis", label: "Remarques", kind: "textarea", row: 75, wide: true },
      { key: "UtilisationsBisBisBis", label: "Utilisations", kind: "text", row: 82 },
      { key: "UtilisationsBisBisBisBis", label: "Utilisations", kind: "select", row: 82, options: ["interne","prestataire externe"], requirement: "obligatoire" },
      { key: "NbDUtilisationSemaineBisBis", label: "Nb d'utilisation / semaine", kind: "number", row: 82, requirement: "recommande" },
      { key: "ReglageLePlusUtiliseSur", label: "Réglage le plus utilisé sur le débit d'eau", kind: "text", row: 85, requirement: "facultatif" },
      { key: "DosageEtNomDuDetergent", label: "Dosage et nom du détergent utilisé", kind: "text", row: 88, requirement: "facultatif" },
      { key: "TemperatureDeLavageLaPlusBisBis", label: "Température de lavage la plus fréquente", kind: "text", row: 91, requirement: "facultatif" },
      { key: "NbDeRemplissageDuReservoir", label: "Nb de remplissage du réservoir eau propre à chaque utilisation", kind: "number", row: 91, requirement: "facultatif" },
      { key: "SurfacesNettoyees", label: "Surfaces nettoyées", kind: "number", row: 94 },
      { key: "SurfaceNettoyeeParUtilisation", label: "Surface nettoyée (m²) par utilisation", kind: "number", row: 94, unit: "m²", requirement: "facultatif" },
      { key: "TypeDeZoneLavee", label: "Type de zone lavée", kind: "text", row: 94, requirement: "recommande" },
      { key: "TypeDeSalissuresRetrouveesDans", label: "Type de salissures retrouvées dans cette zone (sèches, grasses, humides, biologiques, lourdes (huile, boue))", kind: "text", row: 97, requirement: "facultatif" },
      { key: "ExigenceDePropreteDeLa", label: "Exigence de propreté de la zone", kind: "text", row: 97, requirement: "recommande" },
      { key: "TypeDAutolaveuse", label: "Type d'autolaveuse", kind: "select", row: 100, options: ["autotractée","autoportée","industrielle"], requirement: "recommande" },
      { key: "TypeDeBrosses", label: "Type de brosses", kind: "select", row: 100, options: ["disque","rouleau","autre"], requirement: "recommande" },
      { key: "MarqueEtModeleBisBis", label: "Marque et modèle", kind: "text", row: 103, requirement: "facultatif" },
      { key: "LargeurDeTravail", label: "Largeur de travail", kind: "text", row: 103, requirement: "recommande" },
      { key: "DateDAchat", label: "Date d'achat", kind: "text", row: 106, requirement: "facultatif" },
      { key: "TypeDAlimentationElectrique", label: "Type d'alimentation électrique", kind: "select", row: 106, options: ["sur batterie","câble d'alimentation"], requirement: "facultatif" },
      { key: "VolumeReservoirEauPropre", label: "Volume réservoir eau propre", kind: "number", row: 109, unit: "L", requirement: "recommande" },
      { key: "NumeroDuRobinetUtilisePour", label: "Numéro du robinet utilisé pour le remplissage", kind: "text", row: 109, requirement: "recommande" },
      { key: "VolumeReservoirEauSale", label: "Volume réservoir eau sale", kind: "number", row: 112, unit: "L", requirement: "recommande" },
      { key: "LieuDeVidangeDesEaux", label: "Lieu de vidange des eaux sales", kind: "text", row: 112, requirement: "recommande" },
      { key: "EtatVisuelDeLaMachineBisBis", label: "Etat visuel de la machine", kind: "text", row: 115, requirement: "recommande" },
      { key: "DysfonctionnementsObservesBisBis", label: "Dysfonctionnements observés", kind: "textarea", row: 115, wide: true, requirement: "recommande" },
      { key: "ProceduresDEntretienDeLa", label: "Procédures d'entretien de la machine et fréquence", kind: "text", row: 118, requirement: "facultatif" },
      { key: "RemarquesBisBis", label: "Remarques", kind: "textarea", row: 121, wide: true },
      { key: "TypeDeMaterielDeLavage", label: "Type de matériel de lavage", kind: "select", row: 129, options: ["balai serpillère à franges (ou balai espagnol)","balai à plat classique","balai à plat avec microfibres pré-imprégnées","balai à plat avec microfibre jetables","balai brosse","balai avec réservoir (spray mop)","Nettoyeur haute-pression (Karcher)","balais à vapeur","Nettoyage au jet","autre"], requirement: "obligatoire" },
      { key: "PresenceDUnProtocoleDe", label: "Présence d'un protocole de nettoyage", kind: "select", row: 129, options: ["Oui","Non"], requirement: "obligatoire" },
      { key: "ListerLesEquipementsAssociesAu", label: "Lister les équipements associés au matériel de lavage", kind: "text", row: 132, requirement: "obligatoire" },
      { key: "ListerLeNomDuDetergent", label: "Lister le nom du détergent utilisé et son dosage", kind: "text", row: 135, requirement: "recommande" },
      { key: "TypeDeZoneLaveeBis", label: "Type de zone lavée", kind: "text", row: 138, requirement: "recommande" },
      { key: "TypeDeSurface", label: "Type de surface", kind: "select", row: 138, options: ["carrelage (grès, faïence)","pierre (marbre, granit, travertin)","résine époxy / polyuréthane","béton ciré","béton brut","parquet massif","parquet contrecollé","bois stratifié","Linoléum","PVC / vinyle","Moquette en rouleau","dalles de moquette","autre"], requirement: "facultatif" },
      { key: "SurfaceNettoyeeParUtilisationBis", label: "Surface nettoyée (m²) par utilisation", kind: "number", row: 138, unit: "m²", requirement: "facultatif" },
      { key: "TypeDeSalissuresRetrouveesDansBis", label: "Type de salissures retrouvées dans cette zone (sèches, grasses, humides, biologiques, lourdes (huile, boue))", kind: "text", row: 141, requirement: "facultatif" },
      { key: "ExigenceDePropreteDeLaBis", label: "Exigence de propreté de la zone", kind: "text", row: 141, requirement: "recommande" },
      { key: "UtilisationsBisBisBisBisBis", label: "Utilisations", kind: "text", row: 144 },
      { key: "NbDeLavageParSemaine", label: "Nb de lavage par semaine", kind: "number", row: 144, requirement: "recommande" },
      { key: "NbDeSeauxUtilisesA", label: "Nb de seaux utilisés à chaque lavage", kind: "number", row: 144, requirement: "recommande" },
      { key: "VolumeDesSeauxUtilises", label: "Volume des seaux utilisés", kind: "number", row: 147, unit: "L", requirement: "recommande" },
      { key: "NumeroDuRobinetUtilisePourBis", label: "Numéro du robinet utilisé pour le remplissage", kind: "text", row: 147, requirement: "recommande" },
      { key: "RincageDuSol", label: "Rinçage du sol", kind: "select", row: 150, options: ["pas de rinçage","rinçage systématique","rinçage ponctuel"], requirement: "facultatif" },
      { key: "LieuDeVidangeDesEauxBis", label: "Lieu de vidange des eaux sales", kind: "text", row: 150, requirement: "facultatif" },
      { key: "EtatVisuelDesEquipements", label: "Etat visuel des équipements*", kind: "text", row: 153, requirement: "recommande" },
      { key: "DysfonctionnementsObservesBisBisBis", label: "Dysfonctionnements observés", kind: "textarea", row: 153, wide: true, requirement: "recommande" },
      { key: "ProceduresDeRemplacementDesEquipements", label: "Procédures de remplacement des équipements et d'achat des consommables", kind: "text", row: 156, requirement: "facultatif" },
      { key: "RemarquesBisBisBis", label: "Remarques", kind: "textarea", row: 159, wide: true },
    ],
  },
  {
    key: "structure",
    route: "structure",
    singular: "Structure",
    plural: "Structures",
    listColumns: ["Numero","Emplacement","TypeDeLaStructure"],
    fields: [
      { key: "Type", label: "Type", kind: "select", row: 8, options: ["Structure et réseaux","Espace technique aménageable","Ouvrir la suite en fonction du choix"] },
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 11, requirement: "obligatoire" },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 14, requirement: "recommande" },
      { key: "TypeDePlanchers", label: "Type de planchers", kind: "select", row: 19, options: ["dalle béton","dalle poutrelle/hourdis","bois","plancher surélevé","dalle structurelle","plots","dalle amovibles","planchers chauffants"], requirement: "facultatif" },
      { key: "SiPlancherAvecVideTechnique", label: "Si plancher avec vide technique, hauteur du vide technique", kind: "number", row: 19, unit: "cm", requirement: "facultatif" },
      { key: "SiPasDeFauxPlafond", label: "Si pas de faux-plafond, hauteur sous plafond", kind: "number", row: 22, unit: "m", requirement: "facultatif" },
      { key: "SiPresenceDUnFaux", label: "Si présence d'un faux-plafond, hauteur disponible dans le plénum", kind: "number", row: 22, unit: "cm", requirement: "facultatif" },
      { key: "TypeDeCloisons", label: "Type de cloisons", kind: "select", row: 25, options: ["légère sur ossature (placo)","maçonnée (brique, parpaing, carreau de plâtre)","alvéolaire (prêtes à poser)","techniques (coupe-feu, acoustique renforcé, hydrofuge)","vitrées","démontable/modulaire","bois"], requirement: "facultatif" },
      { key: "EmplacementDesGainesTechniques", label: "Emplacement des gaines techniques", kind: "text", row: 25, requirement: "facultatif" },
      { key: "LeReseauDEauPotable", label: "Le réseau d'eau potable passe actuellement dans", kind: "select", row: 28, options: ["des faux-plafonds","des gaines techniques","des vides sanitaires","des trémies","en apparent","la dalle","autre"], requirement: "recommande" },
      { key: "PossibiliteDInstallerUnReseau", label: "Possibilité d'installer un réseau supplémentaire dans les gaines techniques ou le faux-plafond ?", kind: "text", row: 28, requirement: "facultatif" },
      { key: "PresenceDeColonnesDeChute", label: "Présence de colonnes de chute séparées pour les eaux grises ?", kind: "select", row: 31, options: ["oui","non"], requirement: "recommande" },
      { key: "PresenceDUneEvacuationSeparee", label: "Présence d'une évacuation séparée des eaux de lavage, de process et autres ?", kind: "select", row: 31, options: ["Oui","Non"], requirement: "recommande" },
      { key: "PresenceDeTeDeVisite", label: "Présence de Té de visite à intervalles réguliers sur le réseau de collecte", kind: "select", row: 34, options: ["oui","non"], requirement: "facultatif" },
      { key: "LesEauxUseesEtLes", label: "Les eaux usées et les eaux pluviales sont séparées dans le collecteur principal ?", kind: "select", row: 34, options: ["oui","non"], requirement: "obligatoire" },
      { key: "LeReseauDEvacuationDes", label: "Le réseau d'évacuation des eaux usées passe actuellement dans", kind: "select", row: 37, options: ["des faux-plafonds","des gaines techniques","des vides sanitaires","des trémies","en apparent","la dalle","autre"], requirement: "recommande" },
      { key: "EstCeQueTousLes", label: "Est-ce que tous les réseaux EU arrivent au même endroit dans le bâtiment ?", kind: "text", row: 37, requirement: "recommande" },
      { key: "PresenceDUnLocalTechnique", label: "Présence d'un local technique ou sous-sol aménageable ?", kind: "select", row: 42, options: ["oui","oui si on réorganise les espaces","oui avec réserve","non"], requirement: "obligatoire" },
      { key: "UnCamionDeLivraisonDe", label: "Un camion de livraison de cuve et de vidange peut-il se garer à côté de cet espace ?", kind: "select", row: 42, options: ["oui","non"], requirement: "recommande" },
      { key: "EmplacementBis", label: "Emplacement", kind: "text", row: 45, requirement: "obligatoire" },
      { key: "LeRoutePermettantDAcceder", label: "Le route (rue + chemin d'accès) permettant d'accéder à cet espace est il accessible pour un camion de livraison ou de vidange (fils électriques, largeur de route, etc.)?", kind: "select", row: 45, options: ["Oui","Non"], requirement: "recommande" },
      { key: "SurfaceDisponible", label: "Surface disponible", kind: "number", row: 48, unit: "m²", requirement: "recommande" },
      { key: "LesInterventionsTechniquesDeVidange", label: "Les interventions techniques de vidange des cuves peuvent elles se faire durant les horaires d'ouverture sans perturber le fonctionnement du bâtiment ?", kind: "select", row: 48, options: ["Oui","Non"], requirement: "recommande" },
      { key: "HauteurDisponible", label: "Hauteur disponible", kind: "number", row: 51, unit: "m", requirement: "recommande" },
      { key: "CetEspaceEstIlOuvert", label: "Cet espace est-il ouvert au public ?", kind: "select", row: 51, options: ["oui","non"], requirement: "facultatif" },
      { key: "PresenceDUneAlimentationElectrique", label: "Présence d'une alimentation électrique à proximité ?", kind: "select", row: 54, options: ["oui","non"], requirement: "facultatif" },
      { key: "UnSystemeDeRelevageSera", label: "Un système de relevage sera-t-il nécessaire entre la collecte et l'espace de stockage ?", kind: "select", row: 54, options: ["oui","non"], requirement: "facultatif" },
      { key: "LeReseau4g5gEst", label: "Le réseau 4G/5G est-il disponible dans cet espace ?", kind: "select", row: 57, options: ["oui","non"], requirement: "facultatif" },
      { key: "UnByPassVersLe", label: "Un by-pass vers le réseau d'eaux usées est-il possible ?", kind: "select", row: 57, options: ["oui","non"], requirement: "facultatif" },
      { key: "LEspaceEstIlVentile", label: "L'espace est-il ventilé ?", kind: "select", row: 60, options: ["oui","non"], requirement: "facultatif" },
      { key: "CetEspaceEstIlEquipe", label: "Cet espace est-il équipé d'un point d'eau potable ?", kind: "select", row: 60, options: ["oui","non"], requirement: "facultatif" },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 65, wide: true },
    ],
  },
  {
    key: "ventilation_batiment",
    route: "ventilation",
    singular: "Ventilation",
    plural: "Ventilation",
    listColumns: ["Numero","SystemeDeVentilation","EmplacementDuSysteme"],
    fields: [
      { key: "Ventilation", label: "Ventilation", kind: "text", row: 6 },
      { key: "SystemeDeVentilation", label: "Système de ventilation", kind: "select", row: 11, options: ["insuflation","ventilation naturelle","VMC simple flux autoréglable","VMC simple flux hygroréglable","VMC double flux","CTA simple flux","CTA double flux","Ne sait pas","Autre"], requirement: "obligatoire" },
      { key: "EmplacementDuSysteme", label: "Emplacement du système", kind: "text", row: 19, requirement: "recommande" },
      { key: "AnneeDInstallation", label: "Année d'installation", kind: "number", row: 23, requirement: "facultatif" },
      { key: "SystemeEnFonctionnementLeJour", label: "Système en fonctionnement le jour de l'audit", kind: "boolean", row: 27, requirement: "recommande" },
      { key: "DegradationsDysfontionnementObserves", label: "Dégradations / dysfontionnement observés", kind: "text", row: 31, requirement: "recommande" },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 35, wide: true },
    ],
  },
  {
    key: "incendie",
    route: "incendie",
    singular: "Incendie",
    plural: "Incendie",
    listColumns: ["Numero","Emplacement","PrecisionEmplacement"],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 8, requirement: "obligatoire" },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 11, requirement: "recommande" },
      { key: "NombreDeRia", label: "Nombre de RIA ?", kind: "number", row: 16, requirement: "obligatoire" },
      { key: "NombreDeSprinkler", label: "Nombre de sprinkler ?", kind: "number", row: 16, requirement: "obligatoire" },
      { key: "PresenceDUnSurpresseurPour", label: "Présence d'un surpresseur pour le réseau incendie ?", kind: "select", row: 19, options: ["oui","non"], requirement: "facultatif" },
      { key: "PresenceDUnSousCompteur", label: "Présence d'un sous-compteur sur le réseau incendie ?", kind: "select", row: 19, options: ["oui","non"], requirement: "recommande" },
      { key: "PresenceDUneReservieIncendie", label: "Présence d'une réservie incendie ?", kind: "select", row: 22, options: ["Oui","Non"], requirement: "obligatoire" },
      { key: "TypeDEauDeLa", label: "Type d'eau de la réserve incendie", kind: "select", row: 22, options: ["eau potable","eau de pluie","eau pluviale","mare"], requirement: "recommande" },
      { key: "VolumeReserveIncendie", label: "Volume réserve incendie", kind: "number", row: 25, unit: "m3", requirement: "recommande" },
      { key: "TestsReglementairesRealisesSurLe", label: "Tests réglementaires réalisés (essais RIA, essais sprinklers, essais pompes) sur le système incendie :", kind: "text", row: 28, requirement: "recommande" },
      { key: "FrequenceDesTests", label: "Fréquence des tests", kind: "select", row: 28, options: ["hebdomadaire","mensuelle","semestriel","annuelle"], requirement: "recommande" },
      { key: "DureeOuvertureEauDurantLes", label: "Durée ouverture eau durant les tests", kind: "number", row: 31, requirement: "recommande" },
      { key: "DebitMoyenMesureDurantLes", label: "Débit moyen mesuré durant les tests", kind: "number", row: 31, unit: "m3/h", requirement: "recommande" },
      { key: "PresenceDePurgesRegulieresDu", label: "Présence de purges régulières du réseau incendie?", kind: "select", row: 34, options: ["Oui","Non"], requirement: "facultatif" },
      { key: "FrequenceDesPurges", label: "Fréquence des purges", kind: "select", row: 34, options: ["hebdomadaire","mensuelle","semestrielle","biannuelle","annuelle","autre"], requirement: "facultatif" },
      { key: "VolumeDEauEstimePar", label: "Volume d'eau estimé par purge", kind: "number", row: 37, unit: "L", requirement: "facultatif" },
      { key: "DestinationDesEauxDeTests", label: "Destination des eaux de tests/purges", kind: "select", row: 37, options: ["rejet au réseau d'assainissement","rejet au réseau pluvial","infiltration à la parcelle"], requirement: "facultatif" },
      { key: "PresenceDUnCarnetDe", label: "Présence d'un carnet de suivi des tests/purges ?", kind: "select", row: 40, options: ["Oui","Non"], requirement: "recommande" },
      { key: "PersonneEnChargeDesTests", label: "Personne en charge des tests/purges", kind: "text", row: 40, requirement: "recommande" },
      { key: "DysfonctionnementsObserves", label: "Dysfonctionnements observés", kind: "textarea", row: 43, wide: true, requirement: "recommande" },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 46, wide: true },
    ],
  },
  {
    key: "toitures",
    route: "toitures",
    singular: "Toiture",
    plural: "Toitures",
    listColumns: ["Numero","Emplacement","SurfaceDeToiture","ToitureAccessible"],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 8, requirement: "obligatoire" },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 11, requirement: "facultatif" },
      { key: "ToitureAccessible", label: "Toiture accessible ?", kind: "select", row: 16, options: ["Oui","Non"], requirement: "obligatoire" },
      { key: "TypeDeToiture", label: "Type de toiture", kind: "select", row: 16, options: ["terrasse","pente","multiple pans"], requirement: "obligatoire" },
      { key: "SurfaceDeToiture", label: "Surface de toiture", kind: "number", row: 16, unit: "m²", requirement: "recommande" },
      { key: "MateriauDeCouverture", label: "Matériau de couverture", kind: "select", row: 19, options: ["tuiles terre cuite","tuiles béton","ardoises","bac acier","zinc","aluminium","membrane bitumineuse","PVC/EPDM","fibrociment","toiture végétalisée","chaume","verre/vitre","polycarbonate","gravier"], requirement: "recommande" },
      { key: "PenteDeToiture", label: "Pente de toiture", kind: "text", row: 19, requirement: "facultatif" },
      { key: "NombreDePansDeToiture", label: "Nombre de pans de toiture", kind: "number", row: 19, requirement: "recommande" },
      { key: "PresenceDObstacles", label: "Présence d'obstacles", kind: "text", row: 22, requirement: "facultatif" },
      { key: "SiFibrocimentPresenceDAmiante", label: "Si fibrociment, présence d'amiante ?", kind: "boolean", row: 25, requirement: "recommande" },
      { key: "PresenceDePlombOuMetaux", label: "Présence de plomb ou métaux lourds", kind: "select", row: 25, options: ["Oui","Non"], requirement: "recommande" },
      { key: "PresenceDeTraitement", label: "Présence de traitement", kind: "select", row: 25, options: ["oui","non"], requirement: "recommande" },
      { key: "EtatDeLaToiture", label: "Etat de la toiture", kind: "text", row: 28, requirement: "facultatif" },
      { key: "ArbresAProximitePouvantApporter", label: "Arbres à proximité pouvant apporter des feuilles ?", kind: "select", row: 31, options: ["Oui","Non"], requirement: "facultatif" },
      { key: "SourcesDePollutionAProximite", label: "Sources de pollution à proximité", kind: "select", row: 31, options: ["oui","non"], requirement: "facultatif" },
      { key: "TypeDeGouttieres", label: "Type de gouttières", kind: "select", row: 35, options: ["pendante","nantaise","havraise","anglaise"], requirement: "facultatif" },
      { key: "AccessibiliteDesGouttieres", label: "Accessibilité des gouttières", kind: "select", row: 35, options: ["Oui","non"], requirement: "recommande" },
      { key: "MateriauDesGouttieres", label: "Matériau des gouttières", kind: "select", row: 35, options: ["PVC","Zinc","aluminium","béton","acier galvanisé","plomb","pierre","terre cuite","fonte","cuivre"], requirement: "facultatif" },
      { key: "TypeDeCheneaux", label: "Type de cheneaux", kind: "select", row: 45, options: ["sur un versant","contre un mur","sur entablement","entre deux pans de toiture"], requirement: "facultatif" },
      { key: "AccessibiliteDesCheneaux", label: "Accessibilité des cheneaux", kind: "select", row: 45, options: ["Oui","non"], requirement: "recommande" },
      { key: "MateriauDesGouttieresBis", label: "Matériau des gouttières", kind: "select", row: 45, options: ["PVC","Zinc","aluminium","béton","acier galvanisé","plomb","pierre","terre cuite","fonte","cuivre"], requirement: "facultatif" },
      { key: "EtatDesGouttieresEtCheneaux", label: "Etat des gouttières et chéneaux", kind: "text", row: 56, requirement: "recommande" },
      { key: "TypeDeDescentes", label: "Type de descentes", kind: "select", row: 60, options: ["apparente (façade)","encastrée (mur ou gaine technique)"], requirement: "obligatoire" },
      { key: "NombreDeDescentes", label: "Nombre de descentes", kind: "number", row: 60, requirement: "obligatoire" },
      { key: "Materiau", label: "Matériau", kind: "select", row: 60, options: ["PVC","Zinc","aluminium","acier galvanisé","fonte","cuivre"], requirement: "facultatif" },
      { key: "EtatDesDescentes", label: "Etat des descentes", kind: "text", row: 63, requirement: "recommande" },
      { key: "HauteurDesDescentes", label: "Hauteur des descentes", kind: "number", row: 66, unit: "m", requirement: "facultatif" },
      { key: "DiametreDesDescentes", label: "Diamètre des descentes", kind: "number", row: 66, unit: "m", requirement: "recommande" },
      { key: "PresenceDeRegardsAccessiblesEn", label: "Présence de regards accessibles en pied de descente", kind: "select", row: 70, options: ["Oui","Non"], requirement: "facultatif" },
      { key: "PresenceDAvaloirsEnPied", label: "Présence d'avaloirs en pied de descente", kind: "select", row: 70, options: ["Oui","Non"], requirement: "facultatif" },
      { key: "LesEvacuationsDesDescentesSe", label: "Les évacuations des descentes se regoupent-elles en un seul point ?", kind: "select", row: 73, options: ["Oui","Non"], requirement: "recommande" },
      { key: "PresenceDUneGrilleOu", label: "Présence d'une grille ou crapaudine sur les gouttières", kind: "select", row: 73, options: ["Oui","Non"], requirement: "recommande" },
      { key: "DispositifDePretraitementExistant", label: "Dispositif de prétraitement existant", kind: "select", row: 76, options: ["aucun","séparateur premières pluies","filtre sur descente","filtre au sein d'un regard"], requirement: "facultatif" },
      { key: "SiDispositifDePretraitementNoter", label: "Si dispositif de prétraitement, noter le modèle et la maille de filtration", kind: "text", row: 76, requirement: "facultatif" },
      { key: "EvacuationActuelleDesEauxDe", label: "Evacuation actuelle des eaux de pluie", kind: "select", row: 79, options: ["réseau séparatif pluvial","réseau unitaire","rejet en surface","rejet dans un fossé","noue d'infiltration","puits d'infiltrtion","bassin","autre"], requirement: "recommande" },
      { key: "ContraintesReglementairesLocales", label: "Contraintes réglementaires locales (monuments, PLU,etc.) ?", kind: "text", row: 79, requirement: "facultatif" },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 82, wide: true },
    ],
  },
  {
    key: "piscines",
    route: "piscines",
    singular: "Bassin",
    plural: "Piscines",
    listColumns: ["Numero","Nom","Emplacement","VolumeDuBassin"],
    fields: [
      { key: "NomUsuelDuBassin", label: "Nom usuel du bassin", kind: "text", row: 8, requirement: "recommande" },
      { key: "Emplacement", label: "Emplacement", kind: "select", row: 8, options: ["Intérieure","Extérieure","Extérieure avec possibilté d'être couverte"], requirement: "obligatoire" },
      { key: "PourLesPiscinesIndividuellesFaut", label: "pour les piscines individuelles, faut-il ajouter la période d'utilisation de la piscine dans l'année ?", kind: "text", row: 8 },
      { key: "NbDeJourDOuverture", label: "Nb de jour d'ouverture /an", kind: "number", row: 11 },
      { key: "FrequentationJournaliere", label: "Fréquentation journalière", kind: "number", row: 11 },
      { key: "Utilisateurs", label: "Utilisateurs", kind: "select", row: 11, options: ["(plusieurs réponses possibles)","Tout public","Adultes","Enfants","Adolescents","Personnes âgées","Patients"] },
      { key: "Type", label: "Type", kind: "select", row: 14, options: ["Enterré","Semi-enterrée","Hors sol avec structure","Hors sol tubulaire","Hors sol autoportée"] },
      { key: "AnneeDeConstruction", label: "Année de construction", kind: "number", row: 14 },
      { key: "MateriauxDeConstruction", label: "Matériaux de construction", kind: "text", row: 14 },
      { key: "MateriauxDeRevetement", label: "Matériaux de revêtement", kind: "select", row: 14, options: ["Carrelage","Résine","Liner","Coque","Plaques aluminium","autre"] },
      { key: "TypeDeCouverture", label: "Type de couverture", kind: "select", row: 17, options: ["aucune","bâches à bulles (été)","bâche d'hivernage","couverture à barres (4saisons)","volet roulant automatique","volet roulant manuel","abri","terrasse mobile","autre précisé dans remarques"] },
      { key: "VolumeDuBassin", label: "Volume du bassin", kind: "number", row: 17, unit: "m3" },
      { key: "OrigineEauDuBassin", label: "Origine eau du bassin", kind: "select", row: 17, options: ["eau potable","eau de mer","eau souterraine","eau de pluie","eau pluviale","eau de surface"] },
      { key: "ModeDeRemplissageDuBassin", label: "Mode de remplissage du bassin", kind: "select", row: 17, options: ["manuel","automatique avec flotteur"] },
      { key: "ConsigneApportQuotidienBaigneur", label: "Consigne apport quotidien / baigneur", kind: "number", row: 20, unit: "L" },
      { key: "VolumeDApportQuotidien", label: "Volume d'apport quotidien", kind: "number", row: 20, unit: "L" },
      { key: "TemperatureDeConsigneDeL", label: "Température de consigne de l'air", kind: "number", row: 20, unit: "°C" },
      { key: "TemperatureDeConsigneDuBassin", label: "Température de consigne du bassin", kind: "number", row: 20, unit: "°C" },
      { key: "DesinfectionDeLEau", label: "Désinfection de l'eau", kind: "text", row: 23 },
      { key: "TraitementsAutomatise", label: "Traitements automatisé", kind: "boolean", row: 23 },
      { key: "TypeDeFiltration", label: "Type de filtration", kind: "text", row: 23 },
      { key: "NbDeLavageDeFiltre", label: "Nb de lavage de filtre / mois", kind: "number", row: 26 },
      { key: "VolumeRejeteMois", label: "Volume rejeté / mois", kind: "number", row: 26, unit: "m3" },
      { key: "NbDeVidangeAn", label: "Nb de vidange/an", kind: "number", row: 26 },
      { key: "VolumeRejeteAn", label: "Volume rejeté / an", kind: "number", row: 26, unit: "m3" },
      { key: "PossibiliteDeCreerUneZone", label: "Possibilité de créer une zone de stockage des eaux rejetées", kind: "boolean", row: 29 },
      { key: "PresenceConnueDeFuites", label: "Présence connue de fuites", kind: "boolean", row: 32 },
      { key: "VolumeEstimeDesFuitesAn", label: "Volume estimé des fuites/an", kind: "number", row: 32 },
      { key: "EtatGeneral", label: "Etat général*", kind: "select", row: 32, options: ["Bon","Moyen","Mauvais"] },
      { key: "Dysfonctionnements", label: "Dysfonctionnements", kind: "textarea", row: 35, wide: true },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 38, wide: true },
    ],
  },
  {
    key: "espace_vert_exterieur",
    route: "espaces-exterieurs",
    singular: "Espace extérieur",
    plural: "Espaces extérieurs",
    listColumns: ["Numero","Emplacement"],
    fields: [
      { key: "EmplacementDeLEspaceExterieur", label: "Emplacement de l'espace extérieur concerné", kind: "text", row: 8, requirement: "obligatoire" },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 11, requirement: "recommande" },
      { key: "SurfaceDeCetEspace", label: "Surface de cet espace", kind: "number", row: 15, unit: "m2" },
      { key: "DontSurfaceImpermeable", label: "Dont surface imperméable", kind: "number", row: 15, unit: "m2" },
      { key: "TypeDeGestionDesEaux", label: "Type de gestion des eaux pluviales", kind: "select", row: 15, options: ["aucune (ruissellement libre)","infiltration à la parcelle directe","stockage + infiltraion à la parcelle","stockage + réutilisation","rejet au réseau pluvial enterré","rejet au réseau unitaire enterré","rejet vers le milieu superficiel (fossé, cours d'eau)"] },
      { key: "PossibiliteDeRedirigerCesEaux", label: "Possibilité de rediriger ces eaux pour infiltration sur la parcelle", kind: "boolean", row: 22 },
      { key: "Precision", label: "Précision", kind: "textarea", row: 22, wide: true },
      { key: "PossibiliteDeRedirigerCesEauxBis", label: "Possibilité de rediriger ces eaux pour stockage sur la parcelle", kind: "boolean", row: 25 },
      { key: "PrecisionBis", label: "Précision", kind: "textarea", row: 25, wide: true },
      { key: "UtilisationsDEauSurCet", label: "Utilisations d'eau sur cet espace ?", kind: "select", row: 28, options: ["arrosage","nettoyage"], requirement: "obligatoire" },
      { key: "SurfaceArrosee", label: "Surface arrosée", kind: "number", row: 32, unit: "m2", requirement: "recommande" },
      { key: "TypeDeSurfaceAArroser", label: "Type de surface à arroser", kind: "text", row: 32, requirement: "recommande" },
      { key: "PrecisionsDesVegetauxSurCette", label: "Précisions des végétaux sur cette surface", kind: "text", row: 35, requirement: "facultatif" },
      { key: "ExpositionDeLaParcelle", label: "Exposition de la parcelle", kind: "select", row: 38, options: ["Ensoleillée","Ombragée","Mi-ombragée"] },
      { key: "PenteDeLaParcelle", label: "Pente de la parcelle", kind: "select", row: 38, options: ["nulle","faible","moyenne","forte"] },
      { key: "PresenceDePaillage", label: "Présence de paillage", kind: "boolean", row: 38 },
      { key: "TypeDePaillage", label: "Type de paillage", kind: "select", row: 38, options: ["broyat","minéral","copeaux","paille","autre"] },
      { key: "ModeDArrosage", label: "Mode d'arrosage", kind: "select", row: 41, options: ["Tuyau manuel","Arrosoir","Oyas","Micro asperseur","Arrosage goutte à goutte","Arrosage tuyaux poreux","Tuyères","Arrosage non sélectif","Autre"] },
      { key: "PilotageDeLArrosage", label: "Pilotage de l'arrosage", kind: "select", row: 41, options: ["Manuel","En fonction de la météo","Horloge","Sonde humidité","Connecté"] },
      { key: "PeriodeDArrosageDansLa", label: "Période d'arrosage dans la journée", kind: "select", row: 41, options: ["Matin","Soir","En pleine journée"] },
      { key: "OrigineEauPourLArrosage", label: "Origine eau pour l'arrosage", kind: "select", row: 44, options: ["eau potable","eau de pluie","eau pluviale","eau grise","eau souterraine","eau de surface"] },
      { key: "NumerosDesRobinetsCorrespondants", label: "Numéros des robinets correspondants", kind: "select", row: 44, options: ["depuis la liste des robinets"] },
      { key: "NbDeMoisDArrosage", label: "Nb de mois d'arrosage / an", kind: "number", row: 47 },
      { key: "DureeDUnArrosage", label: "Durée d'un arrosage", kind: "number", row: 47 },
      { key: "NbDArrosageMois", label: "Nb d'arrosage / mois", kind: "number", row: 47 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 50, wide: true, requirement: "facultatif" },
      { key: "Utilisation", label: "Utilisation", kind: "text", row: 54, requirement: "recommande" },
      { key: "ModeDeNettoyage", label: "Mode de nettoyage", kind: "select", row: 54, options: L.MODE_NETTOYAGE, requirement: "recommande" },
      { key: "MotifDuNettoyage", label: "Motif du nettoyage", kind: "select", row: 54, options: ["esthétique","hygiène","sécurité","entretien","autre"], requirement: "recommande" },
      { key: "Precisions", label: "Précisions", kind: "textarea", row: 57, wide: true, requirement: "facultatif" },
      { key: "OrigineDeLEau", label: "Origine de l'eau", kind: "select", row: 60, options: ["eau potable","eau de pluie","eau pluviale","eau grise","eau souterraine"], requirement: "recommande" },
      { key: "NumerosDesRobinetsCorrespondantsBis", label: "Numéros des robinets correspondants", kind: "select", row: 60, options: ["depuis la liste des robinets"], requirement: "recommande" },
      { key: "DureeDUnNettoyage", label: "Durée d'un nettoyage", kind: "number", row: 63, requirement: "recommande" },
      { key: "NbDeNettoyageMois", label: "Nb de nettoyage/mois", kind: "number", row: 63, requirement: "recommande" },
      { key: "RemarquesBis", label: "Remarques", kind: "textarea", row: 66, wide: true, requirement: "facultatif" },
      { key: "RemarquesGenerales", label: "Remarques générales", kind: "textarea", row: 69, wide: true },
    ],
  },
  {
    key: "opportunites",
    route: "opportunites",
    singular: "Opportunité",
    plural: "Opportunités",
    listColumns: ["Numero","Emplacement"],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 8, requirement: "obligatoire" },
      { key: "OpportunitesADocumenter", label: "Opportunités à documenter", kind: "select", row: 11, options: ["plusieurs possibles","Eau de pluie","Eaux ménagères et de lavage","Urines"], requirement: "obligatoire" },
      { key: "UtilisationsExterieuresPotentielles", label: "Utilisations extérieures potentielles", kind: "select", row: 15, options: ["arrosage","nettoyage surface","lavage de véhicule","bassin","fontaine","piscine","autre"], requirement: "recommande" },
      { key: "UtilisationsInterieuresPotentielles", label: "Utilisations intérieures potentielles", kind: "select", row: 15, options: ["chasse d'eau","lavage de sol","lavage de linge","process technique","autre"], requirement: "recommande" },
      { key: "AutresUtilisationsInterieuresNonReglementaires", label: "Autres utilisations intérieures non réglementaires", kind: "text", row: 15, requirement: "facultatif" },
      { key: "PossibiliteDImplanterUneOu", label: "Possibilité d'implanter une ou plusieurs cuves sur la parcelle ?", kind: "select", row: 18, options: ["Non","Entérée","Aérienne"], requirement: "recommande" },
      { key: "EspaceDisponiblePourUneCuve", label: "Espace disponible pour une cuve en toiture ?", kind: "select", row: 18, options: ["Oui","Non"], requirement: "recommande" },
      { key: "ContraintesDImplantationDUne", label: "Contraintes d'implantation d'une cuve", kind: "text", row: 21, requirement: "facultatif" },
      { key: "AccesPossibleAuxEnginsEt", label: "Accès possible aux engins et camion de livraison de cuve", kind: "select", row: 24, options: ["Oui","Non"], requirement: "facultatif" },
      { key: "ByPassPossibleDeLa", label: "By-pass possible de la cuve vers une aire d'infiltration ou le réseau pluvial", kind: "select", row: 24, options: ["Oui","Non"], requirement: "facultatif" },
      { key: "QuelEstLePotentielTechnique", label: "Quel est le potentiel technique de réutilisation de l'eau de pluie sur ce bâtiment ? *", kind: "select", row: 27, options: ["fort","moyen","faible","à aproffondir"], requirement: "obligatoire" },
      { key: "ListerLesTypesDEaux", label: "Lister les types d'eaux grises présentes dans le bâtiment", kind: "text", row: 36, requirement: "recommande" },
      { key: "CertainsPointsDEauProduisant", label: "Certains points d'eau produisant des eaux grises sont-ils regroupés ? Si oui, lesquels ?", kind: "text", row: 39, requirement: "facultatif" },
      { key: "SiUnLaveLingeEst", label: "Si un lave-linge est présent, son évacuation peut elle être dissociée des autres évacuations d'eaux grises ?", kind: "select", row: 39, options: ["Oui","Non"], requirement: "facultatif" },
      { key: "ListerLesPrincipauxProduitsChimiques", label: "Lister les principaux produits chimiques utilisés dans le bâtiment qui sont susceptibles de se retrouver dans les eaux ménagères", kind: "text", row: 42, requirement: "recommande" },
      { key: "ListerLesEauxDeLavage", label: "Lister les eaux de lavage produites dans le bâtiment pouvant être réutilisées", kind: "text", row: 45, requirement: "facultatif" },
      { key: "UtilisationsExterieuresPotentiellesBis", label: "Utilisations extérieures potentielles", kind: "select", row: 48, options: ["arrosage","nettoyage surface","lavage de véhicule","bassin","fontaine","autre"], requirement: "recommande" },
      { key: "UtilisationsInterieuresPotentiellesBis", label: "Utilisations intérieures potentielles", kind: "select", row: 48, options: ["chasse d'eau","lavage de sol","process","tours de refroidissement","autre"], requirement: "recommande" },
      { key: "AutresUtilisationsInterieuresNonReglementairesBis", label: "Autres utilisations intérieures non réglementaires", kind: "text", row: 48, requirement: "facultatif" },
      { key: "EstCeQueLeBatiment", label: "Est-ce que le bâtiment est innocupé pendant de longue période (>3 semaines) ?", kind: "select", row: 51, options: ["oui","non"], requirement: "recommande" },
      { key: "QuelEstLePotentielTechniqueBis", label: "Quel est le potentiel technique de recyclage des eaux ménagères sur ce bâtiment ?*", kind: "select", row: 54, options: ["fort","moyen","faible","à aproffondir"], requirement: "obligatoire" },
      { key: "CertainsToilettesSontIlsRegroupes", label: "Certains toilettes sont-ils regroupés dans le bâtiment ? Si oui, lesquels ?", kind: "text", row: 63, requirement: "recommande" },
      { key: "LaMajoriteDesToilettesSont", label: "La majorité des toilettes sont-elles positionnées les unes au-dessus des autres dans le bâtiment ?", kind: "text", row: 63, requirement: "recommande" },
      { key: "ValorisationSurPlaceDesNutriments", label: "Valorisation sur place des nutriments intéressante (espaces verts, potager, etc.) ?", kind: "select", row: 66, options: ["oui","non"], requirement: "facultatif" },
      { key: "APremiereVueQuelEst", label: "A première vue, quel est la taille du gisement urine estimé (nombre de passage dans les toilettes) ?", kind: "select", row: 66, options: ["faible","moyen","élevé","ne sait pas"], requirement: "recommande" },
      { key: "QuelEstLePotentielTechniqueBisBis", label: "Quel est le potentiel technique de collecte des urines dans ce bâtiment ?", kind: "select", row: 69, options: ["fort","moyen","faible","à aproffondir"], requirement: "obligatoire" },
      { key: "PresenceDUnLieuInteressant", label: "Présence d'un lieu intéressant pour valoriser les nutriments à proximité du bâtiment ?", kind: "select", row: 69, options: ["Oui","Non"], requirement: "facultatif" },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 77, wide: true },
    ],
  },
  {
    key: "autre",
    route: "autre",
    singular: "Autre",
    plural: "Autres",
    listColumns: ["Numero","Choix","Nom","Emplacement"],
    fields: [
      { key: "Choix", label: "Choix", kind: "select", row: 8, options: ["ouvrant les champs à la suite en question :","Autre information","Autre utilisation de l'eau"], requirement: "obligatoire" },
      { key: "Nom", label: "Nom", kind: "text", row: 11, requirement: "obligatoire" },
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 14, requirement: "obligatoire" },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 17, requirement: "facultatif" },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 56, wide: true },
    ],
  },
];

/** Retrouve une entité par sa clé de stockage. */
export function entityByKey(key: string): EntityDef | undefined {
  return AUDIT_SCHEMA.find((e) => e.key === key);
}

/** Retrouve une entité par son segment d'URL. */
export function entityByRoute(route: string): EntityDef | undefined {
  return AUDIT_SCHEMA.find((e) => e.route === route);
}
