import { EntityDef } from './field.models';
import * as L from './value-lists';

/**
 * Schéma de la partie technique — GÉNÉRÉ depuis `audit_technique.xlsx`.
 *
 * `row` reproduit le numéro de ligne du tableau Excel : les champs partageant
 * la même valeur sont affichés côte à côte, comme le prescrit le classeur.
 * Les clés de stockage des robinets sont conservées à l'identique.
 *
 * Régénérer avec `node tools/gen-schema.js` après modification du classeur.
 */
export const AUDIT_SCHEMA: EntityDef[] = [
  {
    key: "releve_compteur_general",
    route: "compteur-general",
    singular: "Compteur général",
    plural: "Compteur général",
    single: true,
    listColumns: [],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 6 },
      { key: "ConditionDAcces", label: "Condition d'accès", kind: "text", row: 10 },
      { key: "Marque", label: "Marque", kind: "text", row: 13 },
      { key: "Modele", label: "Modèle", kind: "text", row: 13 },
      { key: "Type", label: "Type", kind: "select", row: 16, options: L.TYPE_COMPTEUR },
      { key: "ClasseMetrologique", label: "Classe métrologique", kind: "select", row: 16, options: L.CLASSE_METROLOGIQUE },
      { key: "NumeroDeSerie", label: "Numéro de série", kind: "text", row: 19 },
      { key: "DiametreNominal", label: "Diamètre Nominal", kind: "number", row: 19, unit: "mm" },
      { key: "AnneeDePose", label: "Année de pose", kind: "number", row: 22 },
      { key: "IndexLeJourDeL", label: "Index le jour de l'audit", kind: "number", row: 22, unit: "m3" },
      { key: "TeletransmissionPrecisez", label: "Télétransmission - Précisez", kind: "text", row: 25 },
      { key: "PresenceDeProtection", label: "Présence de protection (chocs, gel) ?", kind: "text", row: 25 },
      { key: "EtatGeneral", label: "Etat général", kind: "text", row: 28 },
      { key: "ProprietaireDuCompteur", label: "Propriétaire du compteur", kind: "text", row: 31 },
      { key: "OrganesDeReseauAProximite", label: "Organes de réseau à proximité", kind: "text", row: 31 },
      { key: "ClapetAntiRetour", label: "clapet anti-retour", kind: "text", row: 34 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 37, wide: true },
      { key: "FiltreATamis", label: "filtre à tamis ?", kind: "text", row: 37 },
    ],
  },
  {
    key: "sous_compteurs",
    route: "sous-compteurs",
    singular: "Sous-compteur",
    plural: "Sous-compteurs",
    listColumns: ["Numero","Emplacement","AnneeDePose","Teletransmission"],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 7 },
      { key: "ConditionDAcces", label: "Condition d'accès", kind: "text", row: 11 },
      { key: "Marque", label: "Marque", kind: "text", row: 14 },
      { key: "Modele", label: "Modèle", kind: "text", row: 14 },
      { key: "Type", label: "Type", kind: "select", row: 17, options: L.TYPE_COMPTEUR },
      { key: "ClasseMetrologique", label: "Classe métrologique", kind: "select", row: 17, options: L.CLASSE_METROLOGIQUE },
      { key: "NumeroDeSerie", label: "Numéro de série", kind: "text", row: 20 },
      { key: "DiametreNominal", label: "Diamètre Nominal", kind: "number", row: 20, unit: "mm" },
      { key: "AnneeDePose", label: "Année de pose", kind: "number", row: 23 },
      { key: "IndexLeJourDeL", label: "Index le jour de l'audit", kind: "number", row: 23, unit: "m3" },
      { key: "Teletransmission", label: "Télétransmission", kind: "boolean", row: 26 },
      { key: "PresenceDeProtection", label: "Présence de protection ?", kind: "text", row: 26 },
      { key: "PrecisionsTeletransmission", label: "Précisions télétransmission", kind: "text", row: 29 },
      { key: "EtatGeneral", label: "Etat général", kind: "text", row: 29 },
      { key: "ProprietaireDuCompteur", label: "Propriétaire du compteur", kind: "text", row: 32 },
      { key: "OrganesDeReseauAProximite", label: "Organes de réseau à proximité", kind: "text", row: 32 },
      { key: "ClapetAntiRetour", label: "clapet anti-retour", kind: "text", row: 35 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 38, wide: true },
      { key: "FiltreATamis", label: "filtre à tamis ?", kind: "text", row: 38 },
    ],
  },
  {
    key: "reducteurs_de_pression",
    route: "reducteurs-pression",
    singular: "Réducteur de pression",
    plural: "Réducteurs de pression",
    listColumns: ["Numero","ConditionDAcces","Type"],
    fields: [
      { key: "ConditionDAcces", label: "Condition d'accès", kind: "text", row: 12 },
      { key: "Marque", label: "Marque", kind: "text", row: 15 },
      { key: "Modele", label: "Modèle", kind: "text", row: 15 },
      { key: "Type", label: "Type", kind: "select", row: 18, options: L.TYPE_REDUCTEUR_PRESSION },
      { key: "DiametreNominal", label: "Diamètre Nominal", kind: "number", row: 18, unit: "mm" },
      { key: "AnneeDePose", label: "Année de pose", kind: "number", row: 21 },
      { key: "PressionAfficheeSIlY", label: "Pression affichée s'il y a un manomètre", kind: "number", row: 21, unit: "bar" },
      { key: "PressionDeConsigneActuelle", label: "Pression de consigne actuelle", kind: "number", row: 24, unit: "bar" },
      { key: "PlageDeReglageDeLa", label: "Plage de réglage de la pression", kind: "number", row: 24, unit: "bar" },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 27, wide: true },
    ],
  },
  {
    key: "reseaux_efs",
    route: "reseaux-efs",
    singular: "Réseau EFS",
    plural: "Réseaux de distribution EFS",
    listColumns: ["Numero"],
    fields: [
      { key: "ReseauEauFroideSanitaire", label: "Réseau Eau Froide Sanitaire", kind: "text", row: 6 },
      { key: "IdemEcs", label: "idem ECS", kind: "text", row: 11 },
      { key: "Bouclage", label: "bouclage ?", kind: "text", row: 11 },
      { key: "MenuDeroulant", label: "menu déroulant", kind: "text", row: 15 },
      { key: "DiametreDesGaines", label: "diamètre des gaines", kind: "number", row: 18, unit: "mm" },
      { key: "PositionnementDuReseauDeDistribution", label: "Positionnement du réseau de distribution", kind: "text", row: 22 },
      { key: "MenuDeroulantBis", label: "menu déroulant ?", kind: "text", row: 24 },
    ],
  },
  {
    key: "reseaux_eau_chaude_sanitaire",
    route: "reseaux-ecs",
    singular: "Réseau ECS",
    plural: "Réseaux de distribution ECS",
    listColumns: ["Numero"],
    fields: [
      { key: "EcartTempDepartRetour", label: "Ecart temp = départ - retour", kind: "text", row: 12 },
      { key: "Champ", label: "(calcul automatique)", kind: "text", row: 12 },
      { key: "MenuDeroulant", label: "menu déroulant", kind: "text", row: 14 },
      { key: "VaseDExpansion", label: "Vase d'expansion", kind: "text", row: 15 },
      { key: "VanneThermostatique", label: "Vanne thermostatique ?", kind: "text", row: 16 },
      { key: "DiametreDesGaines", label: "diamètre des gaines", kind: "number", row: 17, unit: "mm" },
      { key: "FrequenceDesPurges", label: "Fréquence des purges ?", kind: "text", row: 20 },
      { key: "PositionnementDuReseauDeDistribution", label: "Positionnement du réseau de distribution", kind: "text", row: 21 },
      { key: "MenuDeroulantBis", label: "menu déroulant ?", kind: "text", row: 23 },
      { key: "CarnetsDeMesuresSanitairesCf", label: "Carnets de mesures sanitaires ? Cf questionnaire pré-diagnostic", kind: "text", row: 24 },
      { key: "PeutImpacterLesPrecoSur", label: "peut impacter les préco sur les robinets, les purges etc...", kind: "text", row: 24 },
      { key: "PartieCalorifugeage", label: "Partie calorifugeage", kind: "text", row: 25 },
      { key: "OuiNonNeSaitPas", label: "oui / non / ne sait pas", kind: "text", row: 27 },
      { key: "EpaisseurDeLIsolant", label: "épaisseur de l'isolant", kind: "number", row: 30, unit: "mm" },
      { key: "VideSanitaire", label: "vide sanitaire", kind: "text", row: 32 },
      { key: "Autres", label: "autres", kind: "text", row: 34 },
      { key: "AutresBis", label: "autres", kind: "text", row: 34 },
      { key: "OuiNonNeSaitPasBis", label: "oui / non / ne sait pas", kind: "text", row: 35 },
      { key: "BonMoyenDegrade", label: "Bon / moyen / dégradé", kind: "text", row: 39 },
    ],
  },
  {
    key: "production_ecs",
    route: "production-ecs",
    singular: "Production ECS",
    plural: "Production ECS",
    listColumns: ["Numero"],
    fields: [
      { key: "NumeroDeReseauAssocie", label: "Numéro de réseau associé", kind: "text", row: 9 },
      { key: "SystemeDeProductionDEcs", label: "Système de production d'ECS", kind: "text", row: 13 },
      { key: "APreciser", label: "A préciser", kind: "text", row: 15 },
      { key: "NonConnue", label: "Non connue", kind: "text", row: 16 },
      { key: "PuissanceDuGenerateur", label: "Puissance du générateur", kind: "text", row: 21 },
      { key: "ModeDePilotage", label: "Mode de pilotage ?", kind: "text", row: 31 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 37, wide: true },
    ],
  },
  {
    key: "stockage_ecs",
    route: "stockage-ecs",
    singular: "Stockage ECS",
    plural: "Stockage ECS",
    listColumns: ["Numero"],
    fields: [
      { key: "NumeroReseauEcsAssocie", label: "Numéro réseau ECS associé", kind: "text", row: 10 },
    ],
  },
  {
    key: "equipements_ecs",
    route: "equipements-ecs",
    singular: "Équipement ECS",
    plural: "Équipements ECS",
    listColumns: ["Numero","Emplacement"],
    fields: [
      { key: "SystemeDEcs", label: "Système d'ECS", kind: "text", row: 9 },
      { key: "ProductionDEcs", label: "Production d'ECS", kind: "text", row: 9 },
      { key: "ChauffeEauSolaire", label: "Chauffe-eau solaire", kind: "text", row: 12 },
      { key: "EspacesAlimentesEnEcs", label: "Espaces alimentés en ECS", kind: "text", row: 17 },
      { key: "PointsDEauOuCircuit", label: "Points d'eau ou circuit ?", kind: "text", row: 24 },
    ],
  },
  {
    key: "robinets",
    route: "robinets",
    singular: "Robinet",
    plural: "Robinets",
    listColumns: ["Numero","Emplacement","Type","Debit"],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 7 },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 10 },
      { key: "Usages", label: "Usages", kind: "text", row: 14 },
      { key: "Type", label: "Type", kind: "select", row: 14, options: L.TYPE_ROBINET },
      { key: "Commande", label: "Commande", kind: "select", row: 17, options: L.COMMANDE_ROBINET },
      { key: "Temporisation", label: "Temporisation", kind: "select", row: 17, options: L.TEMPORISATION },
      { key: "PresenceDUnCoolStart", label: "Présence d'un cool-start", kind: "boolean", row: 17 },
      { key: "Debit", label: "Débit en sortie du robinet", kind: "number", row: 20, unit: "L/min" },
      { key: "PresenceReducteur", label: "Présence d'un réducteur de débit", kind: "boolean", row: 20 },
      { key: "TempsECS", label: "Temps obtention ECS", kind: "number", row: 23, unit: "s" },
      { key: "NumeroReseauECS", label: "Numéro réseau ECS d'appartenance", kind: "text", row: 23 },
      { key: "DiametreNominalDeLAlimentation", label: "Diamètre Nominal de l'alimentation", kind: "number", row: 26, unit: "mm" },
      { key: "MateriauDuTuyauDAlimentation", label: "Matériau du tuyau d'alimentation", kind: "select", row: 26, options: L.MATERIAU_TUYAU },
      { key: "NbUtilisationSemaine", label: "Nombre d'utlisation/semaine", kind: "number", row: 29 },
      { key: "NbEquipementIdentique", label: "Nombre d'équipements identiques", kind: "number", row: 29 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 32, wide: true },
    ],
  },
  {
    key: "douches_baignoires",
    route: "douches-baignoires",
    singular: "Douche / Baignoire",
    plural: "Douches et baignoires",
    listColumns: ["Numero","ChoixDeLEquipement","Emplacement","NumeroRobinetCorrespondant"],
    fields: [
      { key: "ChoixDeLEquipement", label: "Choix de l'équipement", kind: "select", row: 7, options: L.TYPE_EQUIPEMENT_DOUCHE },
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 7 },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 10 },
      { key: "NumeroRobinetCorrespondant", label: "Numéro robinet correspondant", kind: "text", row: 14 },
      { key: "TypeDePommeau", label: "Type de pommeau", kind: "select", row: 14, options: L.TYPE_POMMEAU },
      { key: "Usages", label: "Usages", kind: "text", row: 17 },
      { key: "BaignoireIndiquerSesDimensions", label: "Baignoire - Indiquer ses dimensions", kind: "text", row: 17 },
      { key: "DebitEnSortieDuPommeau", label: "Débit en sortie du pommeau", kind: "number", row: 20, unit: "L/min" },
      { key: "PresenceDUnReducteurDe", label: "Présence d'un réducteur de débit", kind: "boolean", row: 20 },
      { key: "NombreDUtlisationSemaine", label: "Nombre d'utlisation/semaine", kind: "number", row: 23 },
      { key: "NombreDEquipementIdentique", label: "Nombre d'équipement identique", kind: "number", row: 23 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 26, wide: true },
    ],
  },
  {
    key: "wc",
    route: "wc",
    singular: "WC",
    plural: "WC",
    listColumns: ["Numero","Type","Emplacement"],
    fields: [
      { key: "Type", label: "Type", kind: "select", row: 7, options: L.TYPE_WC },
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 7 },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 10 },
      { key: "TypeDeToiletteOuUrinoir", label: "Type de toilette ou urinoir", kind: "text", row: 14 },
      { key: "ReferenceDuModeleSiConnu", label: "Référence du modèle si connu", kind: "text", row: 14 },
      { key: "TypeDAssise", label: "Type d'assise", kind: "text", row: 17 },
      { key: "Usagers", label: "Usagers", kind: "text", row: 17 },
      { key: "AnneeDInstallation", label: "Année d'installation", kind: "number", row: 20 },
      { key: "DateDernierReglageChasseD", label: "Date dernier réglage chasse d'eau", kind: "text", row: 23 },
      { key: "TypeDeReservoirDeChasse", label: "Type de réservoir de chasse", kind: "text", row: 23 },
      { key: "VolumeChasse", label: "Volume chasse", kind: "number", row: 26 },
      { key: "VolumeChasseEstimeOuConnu", label: "Volume chasse estimé ou connu", kind: "number", row: 26 },
      { key: "CommandeDeLaChasse", label: "Commande de la chasse", kind: "select", row: 29, options: L.COMMANDE_CHASSE },
      { key: "TemporisationDeLEcoulement", label: "Temporisation de l'écoulement", kind: "select", row: 29, options: L.TEMPORISATION_ECOULEMENT },
      { key: "DureeDeLEcoulementOu", label: "Durée de l'écoulement(s) ou remplissage chasse", kind: "number", row: 32, unit: "s" },
      { key: "NombreDEquipementIdentique", label: "Nombre d'équipement identique", kind: "number", row: 32 },
      { key: "OrigineDeLEau", label: "Origine de l'eau", kind: "text", row: 35 },
      { key: "VolumeEauNcDisponible", label: "Volume eau NC disponible", kind: "number", row: 35, unit: "L" },
      { key: "Ventilation", label: "Ventilation ?", kind: "text", row: 38 },
      { key: "TesterLaPressionAL", label: "Tester la pression à l'ouverture de la porte", kind: "text", row: 38 },
      { key: "DisponibiliteDUnLocalA", label: "Disponibilité d'un local à proximité", kind: "text", row: 41 },
      { key: "Dysfonctionnements", label: "Dysfonctionnements", kind: "textarea", row: 44, wide: true },
      { key: "EtatVisuelGeneralDesSanitaires", label: "Etat visuel général des sanitaires", kind: "text", row: 44 },
      { key: "DysfonctionnementsBis", label: "Dysfonctionnements", kind: "textarea", row: 47, wide: true },
      { key: "EtatVisuelGeneralDesSanitairesBis", label: "Etat visuel général des sanitaires", kind: "text", row: 47 },
      { key: "EstCeQueCertainesToilettes", label: "Est-ce que certaines toilettes ont un mur qui donne sur l'extérieur ?", kind: "text", row: 50 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 53, wide: true },
    ],
  },
  {
    key: "ventilation_batiment",
    route: "ventilation",
    singular: "Ventilation",
    plural: "Ventilation",
    listColumns: ["Numero"],
    fields: [
      { key: "SystemeDeVentilation", label: "Système de ventilation", kind: "text", row: 9 },
      { key: "MenuLePlusSimple", label: "Menu le plus simple", kind: "text", row: 9 },
      { key: "VentilationMecaniqueSimpleFlux", label: "Ventilation mécanique simple flux", kind: "text", row: 12 },
      { key: "EspacesVentiles", label: "Espaces ventilés", kind: "text", row: 13 },
      { key: "VentilationMecaniqueDoubleFlux", label: "Ventilation mécanique double flux", kind: "text", row: 13 },
    ],
  },
  {
    key: "piscines",
    route: "piscines",
    singular: "Piscine",
    plural: "Piscines",
    listColumns: ["Numero","Nom","Emplacement"],
    fields: [
      { key: "Nom", label: "Nom", kind: "text", row: 7 },
      { key: "Emplacement", label: "Emplacement", kind: "select", row: 7, options: ["Intérieure","Extérieure","Extérieure avec possibilté d'être couverte"] },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 10 },
      { key: "AnneeDeConstruction", label: "Année de construction", kind: "number", row: 13 },
      { key: "AnneeDeRenovation", label: "Année de rénovation", kind: "number", row: 13 },
      { key: "PresenceConnueDeFuites", label: "Présence connue de fuites", kind: "boolean", row: 13 },
      { key: "VolumeEstimeDesFuitesAn", label: "Volume estimé des fuites/an", kind: "select", row: 13, options: ["non concerné","manuelle","à pédale","à détection","à pas de temps","écoulement en continu"] },
      { key: "VolumeDuBassin", label: "Volume du bassin", kind: "number", row: 16, unit: "m3" },
      { key: "UtilisationDuBassin", label: "Utilisation du bassin", kind: "text", row: 16 },
      { key: "NbDeJourDOuverture", label: "Nb de jour d'ouverture /an", kind: "number", row: 16 },
      { key: "FrequentationJournaliere", label: "Fréquentation journalière", kind: "number", row: 16 },
      { key: "ConsigneApportQuotidienBaigneur", label: "Consigne apport quotidien / baigneur", kind: "number", row: 19, unit: "L" },
      { key: "VolumeDApportQuotidien", label: "Volume d'apport quotidien", kind: "number", row: 19, unit: "L" },
      { key: "OrigineDeLEauDu", label: "Origine de l'eau du bassin", kind: "text", row: 19 },
      { key: "DesinfectionDeLEau", label: "Désinfection de l'eau", kind: "text", row: 22 },
      { key: "TemperatureDeConsigneDuBassin", label: "Température de consigne du bassin", kind: "number", row: 22, unit: "°C" },
      { key: "NbDeLavageDeFiltre", label: "Nb de lavage de filtre / mois", kind: "number", row: 25 },
      { key: "VolumeRejeteMois", label: "Volume rejeté / mois", kind: "number", row: 25, unit: "m3" },
      { key: "NbDeVidangeAn", label: "Nb de vidange/an", kind: "number", row: 25 },
      { key: "VolumeRejete", label: "Volume rejeté", kind: "number", row: 25, unit: "m3" },
      { key: "VolumeDEauDevantEtre", label: "Volume d'eau devant être rejetées réutilisé/stocké", kind: "number", row: 28, unit: "m3" },
      { key: "PossibiliteDeCreerUneZone", label: "Possibilité de créer une zone de stockage des eaux rejetées", kind: "boolean", row: 28 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 31, wide: true },
    ],
  },
  {
    key: "collecte_eau_pluie",
    route: "collecte-eau-pluie",
    singular: "Collecte d'eau de pluie",
    plural: "Collecte d'eau de pluie",
    single: true,
    listColumns: [],
    fields: [
      { key: "Nom", label: "Nom", kind: "text", row: 7 },
      { key: "Emplacement", label: "Emplacement", kind: "select", row: 7, options: ["Intérieure","Extérieure","Extérieure avec possibilté d'être couverte"] },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 10 },
      { key: "AnneeDeConstruction", label: "Année de construction", kind: "number", row: 13 },
      { key: "AnneeDeRenovation", label: "Année de rénovation", kind: "number", row: 13 },
      { key: "PresenceConnueDeFuites", label: "Présence connue de fuites", kind: "boolean", row: 13 },
      { key: "VolumeEstimeDesFuitesAn", label: "Volume estimé des fuites/an", kind: "select", row: 13, options: ["non concerné","manuelle","à pédale","à détection","à pas de temps","écoulement en continu"] },
      { key: "VolumeDuBassin", label: "Volume du bassin", kind: "number", row: 16, unit: "m3" },
      { key: "UtilisationDuBassin", label: "Utilisation du bassin", kind: "text", row: 16 },
      { key: "NbDeJourDOuverture", label: "Nb de jour d'ouverture /an", kind: "number", row: 16 },
      { key: "FrequentationJournaliere", label: "Fréquentation journalière", kind: "number", row: 16 },
      { key: "ConsigneApportQuotidienBaigneur", label: "Consigne apport quotidien / baigneur", kind: "number", row: 19, unit: "L" },
      { key: "VolumeDApportQuotidien", label: "Volume d'apport quotidien", kind: "number", row: 19, unit: "L" },
      { key: "OrigineDeLEauDu", label: "Origine de l'eau du bassin", kind: "text", row: 19 },
      { key: "DesinfectionDeLEau", label: "Désinfection de l'eau", kind: "text", row: 22 },
      { key: "TemperatureDeConsigneDuBassin", label: "Température de consigne du bassin", kind: "number", row: 22, unit: "°C" },
      { key: "NbDeLavageDeFiltre", label: "Nb de lavage de filtre / mois", kind: "number", row: 25 },
      { key: "VolumeRejeteMois", label: "Volume rejeté / mois", kind: "number", row: 25, unit: "m3" },
      { key: "NbDeVidangeAn", label: "Nb de vidange/an", kind: "number", row: 25 },
      { key: "VolumeRejete", label: "Volume rejeté", kind: "number", row: 25, unit: "m3" },
      { key: "VolumeDEauDevantEtre", label: "Volume d'eau devant être rejetées réutilisé/stocké", kind: "number", row: 28, unit: "m3" },
      { key: "PossibiliteDeCreerUneZone", label: "Possibilité de créer une zone de stockage des eaux rejetées", kind: "boolean", row: 28 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 31, wide: true },
    ],
  },
  {
    key: "espace_vert_exterieur",
    route: "espaces-exterieurs",
    singular: "Espace extérieur",
    plural: "Espaces extérieurs",
    listColumns: ["Numero","Emplacement"],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 7 },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 10 },
      { key: "SurfaceAArroser", label: "Surface à arroser", kind: "number", row: 15, unit: "m2" },
      { key: "ModeDArrosage", label: "Mode d'arrosage", kind: "select", row: 15, options: ["Arrosage goutte à goutte","Arrossage tuyaux poreux","Arrossage non sélectif","Autre"] },
      { key: "Precisions", label: "Précisions", kind: "textarea", row: 15, wide: true },
      { key: "PresenceDePaillage", label: "Présence de paillage", kind: "boolean", row: 18 },
      { key: "ArrosageAutomatique", label: "Arrosage automatique", kind: "boolean", row: 18 },
      { key: "ArrosageEnFonctionDeLa", label: "Arrosage en fonction de la météo", kind: "boolean", row: 18 },
      { key: "VegetauxSurCetteSurface", label: "Végétaux sur cette surface", kind: "text", row: 21 },
      { key: "UtilisationDEauNc", label: "Utilisation d'eau NC", kind: "boolean", row: 24 },
      { key: "OrigineEauNc", label: "Origine eau NC", kind: "text", row: 24 },
      { key: "VolumeEauNcDisponible", label: "Volume eau NC disponible", kind: "number", row: 24, unit: "L" },
      { key: "NcNonConventionnelle", label: "NC = non conventionnelle", kind: "text", row: 24 },
      { key: "NbDeMoisDArrosage", label: "Nb de mois d'arrosage / an", kind: "number", row: 27 },
      { key: "DureeDUnArrosage", label: "Durée d'un arrosage", kind: "number", row: 27 },
      { key: "NbDArrosageAL", label: "Nb d'arrosage à l'eau potable / mois", kind: "number", row: 27 },
      { key: "NombreDeRobinetDEau", label: "Nombre de robinet d'eau potable utilisés", kind: "number", row: 30 },
      { key: "NumerosDesRobinetsCorrespondants", label: "Numéros des robinets correspondants", kind: "text", row: 30 },
      { key: "Usage", label: "Usage", kind: "text", row: 34 },
      { key: "ModeDeNettoyage", label: "Mode de nettoyage", kind: "select", row: 34, options: L.MODE_NETTOYAGE },
      { key: "PrecisionsBis", label: "Précisions", kind: "textarea", row: 34, wide: true },
      { key: "UtlisationDEauNc", label: "Utlisation d'eau NC", kind: "boolean", row: 37 },
      { key: "OrigineEauNcBis", label: "Origine eau NC", kind: "text", row: 37 },
      { key: "VolumeEauNcDisponibleBis", label: "Volume eau NC disponible", kind: "number", row: 37, unit: "L" },
      { key: "DureeDUnNettoyage", label: "Durée d'un nettoyage", kind: "number", row: 40 },
      { key: "NbDeNettoyageAL", label: "Nb de nettoyage à l'eau potable/mois", kind: "number", row: 40 },
      { key: "NombreDeRobinetDEauBis", label: "Nombre de robinet d'eau potable utilisés", kind: "number", row: 43 },
      { key: "NumerosDesRobinetsCorrespondantsBis", label: "Numéros des robinets correspondants", kind: "text", row: 43 },
      { key: "UsageBis", label: "Usage", kind: "text", row: 47 },
      { key: "PrecisionsBisBis", label: "Précisions", kind: "textarea", row: 47, wide: true },
      { key: "UtlisationDEauNcBis", label: "Utlisation d'eau NC", kind: "boolean", row: 50 },
      { key: "OrigineEauNcBisBis", label: "Origine eau NC", kind: "text", row: 50 },
      { key: "VolumeEauNcDisponibleBisBis", label: "Volume eau NC disponible", kind: "number", row: 50 },
      { key: "VolumeDEauPotableUtlise", label: "Volume d'eau potable utlisé / mois", kind: "number", row: 53 },
      { key: "FrequenceMois", label: "Fréquence/mois", kind: "text", row: 53 },
      { key: "NombreDeRobinetDEauBisBis", label: "Nombre de robinet d'eau potable utilisés", kind: "number", row: 56 },
      { key: "NumerosDesRobinetsCorrespondantsBisBis", label: "Numéros des robinets correspondants", kind: "text", row: 56 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 59, wide: true },
    ],
  },
];

/** Retrouve une entité par sa clé de stockage. */
export function entityByKey(key: string): EntityDef | undefined {
  return AUDIT_SCHEMA.find((e) => e.key === key);
}

/** Retrouve une entité par son segment d'URL. */
export function entityByRoute(route: string): EntityDef | undefined {
  return AUDIT_SCHEMA.find((e) => e.route === route);
}
