import { EntityDef } from './field.models';
import * as L from './value-lists';

/**
 * Schéma de la partie technique — GÉNÉRÉ depuis `audit_technique.xlsx`.
 *
 * `row` reproduit le numéro de ligne du tableau Excel : les champs partageant
 * la même valeur sont affichés côte à côte, comme le prescrit le classeur.
 * Les clés de stockage des robinets sont conservées à l'identique.
 *
 * Régénérer avec `node tools/gen-schema.js` après modification du classeur.
 */
export const AUDIT_SCHEMA: EntityDef[] = [
  {
    key: "releve_compteur_general",
    route: "compteur-general",
    singular: "Compteur général",
    plural: "Compteur général",
    single: true,
    listColumns: [],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 6 },
      { key: "ConditionDAcces", label: "Condition d'accès", kind: "text", row: 10 },
      { key: "Marque", label: "Marque", kind: "text", row: 13 },
      { key: "Modele", label: "Modèle", kind: "text", row: 13 },
      { key: "Type", label: "Type", kind: "select", row: 16, options: L.TYPE_COMPTEUR },
      { key: "ClasseMetrologique", label: "Classe métrologique", kind: "select", row: 16, options: ["Classe A","Classe B","Classe C","Classe D","R40","R50","R63","R80","R100","R125","R160","R200","R250","R315","R400","R160","R200","R400","R500","R630","R800","Inconnue"] },
      { key: "NumeroDeSerie", label: "Numéro de série", kind: "text", row: 19 },
      { key: "DiametreNominal", label: "Diamètre Nominal", kind: "number", row: 19, unit: "mm" },
      { key: "AnneeDePose", label: "Année de pose", kind: "number", row: 22 },
      { key: "IndexLeJourDeL", label: "Index le jour de l'audit", kind: "number", row: 22, unit: "m3" },
      { key: "Teletransmission", label: "Télétransmission", kind: "boolean", row: 25 },
      { key: "PrecisionsTeletransmission", label: "Précisions télétransmission", kind: "text", row: 25 },
      { key: "PresenceDeProtection", label: "Présence de protection (chocs, gel) ?", kind: "text", row: 28 },
      { key: "EtatGeneral", label: "Etat général*", kind: "select", row: 28, options: ["Bon","Moyen","Mauvais"] },
      { key: "ProprietaireDuCompteur", label: "Propriétaire du compteur", kind: "text", row: 31 },
      { key: "DateDerniereMaintenance", label: "Date dernière maintenance", kind: "text", row: 31 },
      { key: "DysfonctionnementsObserves", label: "Dysfonctionnements observés", kind: "textarea", row: 34, wide: true },
      { key: "OrganesDeReseauAProximite", label: "Organes de réseau à proximité", kind: "text", row: 37 },
      { key: "EnCasDImpossibiliteDe", label: "En cas d'impossibilité de relevé le compteur général - Indiquer les raisons", kind: "textarea", row: 40, wide: true },
      { key: "DispositifRelieAuGtbGtc", label: "Dispositif relié au GTB/GTC ?", kind: "boolean", row: 43 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 46, wide: true },
    ],
  },
  {
    key: "sous_compteurs",
    route: "sous-compteurs",
    singular: "Sous-compteur",
    plural: "Sous-compteurs",
    listColumns: ["Numero","Emplacement","AnneeDePose","Teletransmission"],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 7 },
      { key: "ConditionDAcces", label: "Condition d'accès", kind: "text", row: 11 },
      { key: "Marque", label: "Marque", kind: "text", row: 14 },
      { key: "Modele", label: "Modèle", kind: "text", row: 14 },
      { key: "Type", label: "Type", kind: "select", row: 17, options: L.TYPE_COMPTEUR },
      { key: "ClasseMetrologique", label: "Classe métrologique", kind: "select", row: 17, options: ["Classe A","Classe B","Classe C","Classe D","R40","R50","R63","R80","R100","R125","R160","R200","R250","R315","R400","R160","R200","R400","R500","R630","R800","Inconnue"] },
      { key: "NumeroDeSerie", label: "Numéro de série", kind: "text", row: 20 },
      { key: "DiametreNominal", label: "Diamètre Nominal", kind: "number", row: 20, unit: "mm" },
      { key: "AnneeDePose", label: "Année de pose", kind: "number", row: 23 },
      { key: "IndexLeJourDeL", label: "Index le jour de l'audit", kind: "number", row: 23, unit: "m3" },
      { key: "Teletransmission", label: "Télétransmission", kind: "boolean", row: 26 },
      { key: "PrecisionsTeletransmission", label: "Précisions télétransmission", kind: "text", row: 26 },
      { key: "PresenceDeProtection", label: "Présence de protection (chocs, gel) ?", kind: "text", row: 29 },
      { key: "EtatGeneral", label: "Etat général*", kind: "select", row: 29, options: ["Bon","Moyen","Mauvais"] },
      { key: "ProprietaireDuCompteur", label: "Propriétaire du compteur", kind: "text", row: 32 },
      { key: "DateDerniereMaintenance", label: "Date dernière maintenance", kind: "text", row: 32 },
      { key: "DysfonctionnementsObserves", label: "Dysfonctionnements observés", kind: "textarea", row: 35, wide: true },
      { key: "OrganesDeReseauAProximite", label: "Organes de réseau à proximité", kind: "text", row: 38 },
      { key: "EnCasDImpossibiliteDe", label: "En cas d'impossibilité de relevé le compteur général - Indiquer les raisons", kind: "textarea", row: 41, wide: true },
      { key: "DispoisitifRelieAuGtbGtc", label: "Dispoisitif relié au GTB/GTC ?", kind: "boolean", row: 44 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 47, wide: true },
    ],
  },
  {
    key: "reducteurs_de_pression",
    route: "reducteurs-pression",
    singular: "Réducteur de pression",
    plural: "Réducteurs de pression",
    listColumns: ["Numero","Emplacement","AnneeDePose"],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 8 },
      { key: "ConditionDAcces", label: "Condition d'accès", kind: "text", row: 12 },
      { key: "Marque", label: "Marque", kind: "text", row: 15 },
      { key: "Modele", label: "Modèle", kind: "text", row: 15 },
      { key: "TypeDeReducteursExistantA", label: "Type de réducteurs existant à confirmer par un.e expert.e", kind: "text", row: 18 },
      { key: "Type", label: "Type", kind: "select", row: 18, options: L.TYPE_REDUCTEUR_PRESSION },
      { key: "DiametreNominal", label: "Diamètre Nominal", kind: "number", row: 18, unit: "mm" },
      { key: "AnneeDePose", label: "Année de pose", kind: "number", row: 21 },
      { key: "PressionAfficheeSiManometre", label: "Pression affichée si manomètre", kind: "number", row: 21, unit: "bar" },
      { key: "PressionDeConsigneActuelle", label: "Pression de consigne actuelle", kind: "number", row: 24, unit: "bar" },
      { key: "PlageDeReglageDeLa", label: "Plage de réglage de la pression", kind: "number", row: 24, unit: "bar" },
      { key: "EtatGeneral", label: "Etat général*", kind: "select", row: 27, options: ["Bon","Moyen","Mauvais"] },
      { key: "DateDerniereMaintenance", label: "Date dernière maintenance", kind: "text", row: 27 },
      { key: "OrganesDeReseauAProximite", label: "Organes de réseau à proximité", kind: "text", row: 30 },
      { key: "DysfonctionnementsObserves", label: "Dysfonctionnements observés", kind: "textarea", row: 33, wide: true },
      { key: "DispoisitifRelieAuGtbGtc", label: "Dispoisitif relié au GTB/GTC ?", kind: "boolean", row: 36 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 39, wide: true },
    ],
  },
  {
    key: "surpresseurs",
    route: "surpresseurs",
    singular: "Surpresseur",
    plural: "Surpresseurs",
    listColumns: ["Numero","Emplacement","AnneeDePose"],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 8 },
      { key: "ConditionDAcces", label: "Condition d'accès", kind: "text", row: 12 },
      { key: "Marque", label: "Marque", kind: "text", row: 15 },
      { key: "Modele", label: "Modèle", kind: "text", row: 15 },
      { key: "Type", label: "Type", kind: "text", row: 18 },
      { key: "DiametreNominal", label: "Diamètre Nominal", kind: "number", row: 18, unit: "mm" },
      { key: "AnneeDePose", label: "Année de pose", kind: "number", row: 21 },
      { key: "PressionAfficheeSiManometre", label: "Pression affichée si manomètre", kind: "number", row: 21, unit: "bar" },
      { key: "PressionDeConsigneActuelle", label: "Pression de consigne actuelle", kind: "number", row: 24, unit: "bar" },
      { key: "PlageDeReglageDeLa", label: "Plage de réglage de la pression", kind: "number", row: 24, unit: "bar" },
      { key: "EtatGeneral", label: "Etat général", kind: "select", row: 27, options: ["Bon","Moyen","Mauvais"] },
      { key: "DateDerniereMaintenance", label: "Date dernière maintenance", kind: "text", row: 27 },
      { key: "OrganesDeReseauAProximite", label: "Organes de réseau à proximité", kind: "text", row: 30 },
      { key: "DysfonctionnementsObserves", label: "Dysfonctionnements observés", kind: "textarea", row: 33, wide: true },
      { key: "DispositifRelieAuGtbGtc", label: "Dispositif relié au GTB/GTC ?", kind: "boolean", row: 36 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 39, wide: true },
    ],
  },
  {
    key: "reseaux_eau_chaude_sanitaire",
    route: "reseaux-ecs",
    singular: "Réseau ECS",
    plural: "Réseaux ECS",
    listColumns: ["Numero","MateriauPrincipalDesCanalisations","DiametreDesGaines","Bouclage"],
    fields: [
      { key: "AnneeDInstallation", label: "Année d'installation", kind: "number", row: 8 },
      { key: "MateriauPrincipalDesCanalisations", label: "Matériau principal des canalisations", kind: "select", row: 11, options: ["Cuivre","Multicouche","PER","PEHD","PE","pvc sous pression","acier galvanisé","fonte"] },
      { key: "DiametreDesGaines", label: "Diamètre des gaines", kind: "number", row: 14, unit: "mm" },
      { key: "LongueurTotaleDuReseau", label: "Longueur totale du réseau (si connue)", kind: "text", row: 17 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 20, wide: true },
      { key: "CalorifugeageDesCanalisations", label: "Calorifugeage des canalisations", kind: "select", row: 24, options: ["oui","non","ne sait pas"] },
      { key: "EpaisseurDeLIsolant", label: "Epaisseur de l'isolant", kind: "number", row: 27, unit: "mm" },
      { key: "MateriauxDeLIsolant", label: "Matériaux de l'isolant", kind: "select", row: 30, options: ["laine de verre","laine de roche","papier et platre","polyruéthane","Mousse synthétique (armaflex,PE…)"] },
      { key: "ContinuiteDeLIsolation", label: "Continuité de l'isolation", kind: "select", row: 33, options: ["oui","non","ne sait pas"] },
      { key: "EtatDeLIsolant", label: "Etat de l'isolant*", kind: "select", row: 36, options: ["Bon","Moyen","Mauvais"] },
      { key: "RemarquesBis", label: "Remarques", kind: "textarea", row: 39, wide: true },
      { key: "Bouclage", label: "Bouclage", kind: "select", row: 46, options: ["oui","non","ne sait pas"] },
      { key: "DebitRegleSurLaPompe", label: "Débit réglé sur la pompe/circulateur", kind: "number", row: 49, unit: "l/s" },
      { key: "TemperatureAfficheeDuDepartEcs", label: "Température affichée du départ ECS", kind: "number", row: 52, unit: "°C" },
      { key: "TemperatureAfficheeDuRetourDe", label: "Température affichée du retour de boucle", kind: "number", row: 55, unit: "°C" },
      { key: "EcartDeTemperatureEntreLe", label: "Ecart de température entre le départ et le retour", kind: "number", row: 58, unit: "°C" },
      { key: "MarqueEtModeleDuCirculateur", label: "Marque et modèle du circulateur", kind: "text", row: 62 },
      { key: "ModeDeFonctionnementDuCirculateur", label: "Mode de fonctionnement du circulateur", kind: "select", row: 65, options: ["continu","horloge programmable","piloté par la température","aquastat","GTB","GTC"] },
      { key: "VariationDeVitesseDuCirculateur", label: "Variation de vitesse du circulateur possible", kind: "boolean", row: 68 },
      { key: "DegradationDysfonctionnementsObserves", label: "Dégradation / dysfonctionnements observés", kind: "textarea", row: 71, wide: true },
      { key: "RemarquesBisBis", label: "Remarques", kind: "textarea", row: 74, wide: true },
      { key: "PresenceDUneVanneThermostatique", label: "Présence d'une vanne thermostatique", kind: "select", row: 79, options: ["manuelle","motorisée","non","ne sait pas"] },
      { key: "PresenceDUnClapetAnti", label: "Présence d'un clapet anti-retour", kind: "select", row: 82, options: ["oui","non","ne sait pas"] },
      { key: "PresenceDUnVaseD", label: "Présence d'un vase d'expansion", kind: "select", row: 85, options: ["oui","non","ne sait pas"] },
      { key: "RemarquesBisBisBis", label: "Remarques", kind: "textarea", row: 92, wide: true },
      { key: "PresenceDeBrasMortConnus", label: "Présence de bras mort connus", kind: "select", row: 96, options: ["oui","non","ne sait pas"] },
      { key: "Precisions", label: "Précisions", kind: "text", row: 99 },
      { key: "PresenceDUnePurgeAutomatique", label: "Présence d'une purge automatique", kind: "select", row: 103, options: ["oui","non","ne sait pas"] },
      { key: "ProtocolePourLeRisqueLegionnelle", label: "Protocole pour le risque légionnelle déjà mis en place ?", kind: "select", row: 106, options: ["oui","non","ne sait pas"] },
      { key: "PresenceDUnTraitementComplementaire", label: "Présence d'un traitement complémentaire contre la légionnelle ?", kind: "text", row: 109 },
    ],
  },
  {
    key: "production_stockage_ecs",
    route: "production-stockage-ecs",
    singular: "Production / Stockage ECS",
    plural: "Production / Stockage ECS",
    listColumns: ["Numero","TypeDeSystemeDeProduction","SystemesDeProduction"],
    fields: [
      { key: "NumeroDeReseauEcsAssocie", label: "Numéro de réseau ECS associé", kind: "select", row: 9, options: ["correspondant aux champs \"numéro de réseau ECS\" précedemment remplis"] },
      { key: "TypeDeSystemeDeProduction", label: "Type de système de production/stockage d'ECS", kind: "text", row: 12 },
      { key: "ModeDeProductionStockageD", label: "Mode de production/stockage d'ECS", kind: "text", row: 15 },
      { key: "Type", label: "Type", kind: "text", row: 20 },
      { key: "SystemesDeProduction", label: "Systèmes de production", kind: "select", row: 23, options: ["Chauffe-eau gaz instantané","Accumulateur gaz","Chaudière","Ballon électrique","Chauffe-eau électrique","Chauffe-eau solaire thermique","Solaire photovoltaïque","Système solaire combiné chauffage + ECS","Chauffe-eau thermodynamique individuel (ie PAC)","PAC (indiviuuelle ou collective)","Module thermique d'appartements (MTA)","Kit robinetterie avec module chaufffant","Autre (préciser dans remarques)","Ne sait pas"] },
      { key: "Combustible", label: "Combustible", kind: "select", row: 26, options: ["gaz","fioul","bois","biomasse","réseau de chaleur urbain","ne sait pas","autre"] },
      { key: "MarqueEtModeleDuGenerateur", label: "Marque et modèle du générateur", kind: "text", row: 29 },
      { key: "RegulationPilotageDeLaProduction", label: "Régulation / pilotage de la production", kind: "text", row: 32 },
      { key: "EtatApparentDuGenerateur", label: "Etat apparent du générateur*", kind: "select", row: 35, options: ["Bon","Moyen","Mauvais"] },
      { key: "DegradationDysfonctionnementsObserves", label: "Dégradation / dysfonctionnements observés", kind: "textarea", row: 38, wide: true },
      { key: "EmplacementDuGenerateur", label: "Emplacement du générateur", kind: "text", row: 41 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 44, wide: true },
      { key: "NombreDeBallonDeStockage", label: "Nombre de ballon de stockage", kind: "number", row: 52 },
      { key: "EmplacementDuBallon", label: "Emplacement du (des) ballon(s)", kind: "number", row: 55, unit: "s" },
      { key: "ChauffageDuLocal", label: "Chauffage du local", kind: "text", row: 58 },
      { key: "VolumeTotalDeStockage", label: "Volume total de stockage (L)", kind: "number", row: 61, unit: "L" },
      { key: "MontageDesBallons", label: "Montage des ballons", kind: "text", row: 64 },
      { key: "EtatApparentDuBallons", label: "Etat apparent du (des) ballons*", kind: "text", row: 67 },
      { key: "DegradationDysfonctionnementsObservesBis", label: "Dégradation / dysfonctionnements observés", kind: "textarea", row: 70, wide: true },
      { key: "IsolationDuBallons", label: "Isolation du (des) ballons", kind: "text", row: 78 },
      { key: "ContinuiteDeLIsolantSur", label: "Continuité de l'isolant sur tout le (les) ballons", kind: "select", row: 81, options: ["oui","non","ne sait pas"] },
      { key: "EtatDeLIsolant", label: "Etat de l'isolant*", kind: "select", row: 84, options: ["bon","moyen","mauvais"] },
      { key: "RemarquesBis", label: "Remarques", kind: "textarea", row: 87, wide: true },
      { key: "TemperatureAfficheeSurLeBallon", label: "Température affichée sur le ballon", kind: "number", row: 95, unit: "°C" },
      { key: "PresenceDUneSoupapeDe", label: "Présence d'une soupape de sécurité", kind: "select", row: 100, options: ["oui","non","ne sait pas"] },
      { key: "PresenceDUnVaseD", label: "Présence d'un vase d'expansion entre la soupape de sécurité et le stockage", kind: "select", row: 103, options: ["oui","non","ne sait pas"] },
      { key: "DegradationDysfonctionnementsObservesBisBis", label: "Dégradation / dysfonctionnements observés", kind: "textarea", row: 106, wide: true },
      { key: "RemarquesBisBis", label: "Remarques", kind: "textarea", row: 109, wide: true },
    ],
  },
  {
    key: "robinets",
    route: "robinets",
    singular: "Robinet",
    plural: "Robinets",
    listColumns: ["Numero","Emplacement","Type","Debit"],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 7 },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 10 },
      { key: "Utilisation", label: "Utilisation", kind: "text", row: 14 },
      { key: "Usagers", label: "Usagers", kind: "text", row: 17 },
      { key: "Type", label: "Type", kind: "select", row: 20, options: ["Simple EF","Simple ECS","Mélangeur","Mitigeur classique","Mitigeur thermostatique"] },
      { key: "Commande", label: "Commande", kind: "select", row: 20, options: ["manuelle","fémorale","à pédale","à détection"] },
      { key: "Temporisation", label: "Temporisation", kind: "select", row: 23, options: L.TEMPORISATION },
      { key: "TempsDeLaTemporisation", label: "Temps de la temporisation", kind: "number", row: 23, unit: "s" },
      { key: "AnneeDePose", label: "Année de pose", kind: "number", row: 31 },
      { key: "PresenceDUnLimiteurDe", label: "Présence d'un limiteur de débit", kind: "boolean", row: 31 },
      { key: "Mesure", label: "Mesure", kind: "text", row: 35 },
      { key: "Temps", label: "Temps", kind: "number", row: 35, unit: "s" },
      { key: "Volume", label: "Volume", kind: "number", row: 35, unit: "L" },
      { key: "Debit", label: "Débit", kind: "number", row: 35, unit: "L/min" },
      { key: "1", label: "1", kind: "text", row: 36 },
      { key: "2", label: "2", kind: "text", row: 37 },
      { key: "TemperatureMaxEcs", label: "Température max ECS", kind: "number", row: 40, unit: "°C" },
      { key: "TempsDObtention", label: "Temps d'obtention", kind: "number", row: 40, unit: "s" },
      { key: "NumeroReseauEcsDAppartenance", label: "Numéro réseau ECS d'appartenance", kind: "entity-ref", row: 40, refTo: "reseaux_eau_chaude_sanitaire" },
      { key: "DiametreNominalDeLAlimentation", label: "Diamètre Nominal de l'alimentation", kind: "number", row: 43, unit: "mm" },
      { key: "MateriauDuTuyauDAlimentation", label: "Matériau du tuyau d'alimentation", kind: "select", row: 43, options: L.MATERIAU_TUYAU },
      { key: "EtatGeneral", label: "Etat général*", kind: "select", row: 46, options: ["Bon","Moyen","Mauvais"] },
      { key: "DateDerniereMaintenance", label: "Date dernière maintenance", kind: "text", row: 46 },
      { key: "NombreDUtilisationSemaine", label: "Nombre d'utilisation/semaine", kind: "number", row: 49 },
      { key: "NombreDEquipementsIdentiques", label: "Nombre d'équipements identiques", kind: "number", row: 49 },
      { key: "DysfonctionnementsObserves", label: "Dysfonctionnements observés", kind: "textarea", row: 52, wide: true },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 55, wide: true },
    ],
  },
  {
    key: "douches_baignoires",
    route: "douches-baignoires",
    singular: "Douche / Baignoire",
    plural: "Douches et baignoires",
    listColumns: ["Numero","TypeDEquipement","Emplacement"],
    fields: [
      { key: "TypeDEquipement", label: "Type d'équipement", kind: "select", row: 7, options: ["douche ou baignoire","Affiche ensuite la partie","\"Douche et pommeau\"","ou","\"Baignoire et pommeau\""] },
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 7 },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 10 },
      { key: "Utilisations", label: "Utilisations", kind: "text", row: 14 },
      { key: "AnneeDePose", label: "Année de pose", kind: "number", row: 14 },
      { key: "Usagers", label: "Usagers", kind: "text", row: 17 },
      { key: "NombreDUtilisationSemaine", label: "Nombre d'utilisation/semaine", kind: "number", row: 20 },
      { key: "NombreDEquipementsIdentiques", label: "Nombre d'équipements identiques", kind: "number", row: 20 },
      { key: "ParticularitesDeLaDoucheEncastree", label: "Particularités de la douche (pommeau manuel ou douchette, ciel de pluie, tête de douche fixe ou murale, colonne de douche seule, système mixte (tête + douchette), encastrée, hydromassante (jet latéraux), etc.)", kind: "text", row: 24 },
      { key: "TypeDePommeau", label: "Type de pommeau", kind: "select", row: 27, options: ["Pommeau de douche classique","Pommeau de douche hydroéconome","Pommeau de douche anti-légionnelle","pommeau anti-calcaire"] },
      { key: "JetsDuPommeau", label: "Jets du pommeau", kind: "select", row: 27, options: ["aucune","pluie laminaire","aéré","brumisé","pulsé/massage","concentré/puissant","multi-jets"] },
      { key: "DebitEnSortieDuPommeau", label: "Débit en sortie du pommeau", kind: "number", row: 30, unit: "L/min" },
      { key: "PresenceDUnLimiteurDe", label: "Présence d'un limiteur de débit", kind: "boolean", row: 30 },
      { key: "TemperatureMaxEcs", label: "Température max ECS", kind: "number", row: 33, unit: "°C" },
      { key: "TempsDObtention", label: "Temps d'obtention", kind: "number", row: 33, unit: "s" },
      { key: "NumeroReseauEcsDAppartenance", label: "Numéro réseau ECS d'appartenance", kind: "entity-ref", row: 33, refTo: "reseaux_eau_chaude_sanitaire" },
      { key: "EtatGeneral", label: "Etat général", kind: "select", row: 36, options: ["Bon","Moyen","Mauvais"] },
      { key: "DateDerniereMaintenance", label: "Date dernière maintenance", kind: "text", row: 36 },
      { key: "DysfonctionnementsObserves", label: "Dysfonctionnements observés", kind: "textarea", row: 39, wide: true },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 42, wide: true },
      { key: "MauvaisEtat", label: "Mauvais état", kind: "text", row: 47 },
      { key: "EquipementAncienFuitePermanenteEntartrage", label: "équipement ancien, fuite permanente, entartrage important, flexible abîmé, jets irréguliers en permanence, mauvais état des joints du receveur", kind: "text", row: 47 },
      { key: "ParticularitesDeLaBaignoireEtc", label: "Particularités de la baignoire (sur pieds, portante, encastrée, hydromassante (jet latéraux), etc.)", kind: "text", row: 49 },
      { key: "TypeDePommeauBis", label: "Type de pommeau", kind: "select", row: 52, options: ["Pommeau de douche classique","Pommeau de douche hydroéconome","Pommeau de douche anti-légionnelle","pommeau anti-calcaire"] },
      { key: "JetsDuPommeauBis", label: "Jets du pommeau", kind: "select", row: 52, options: ["aucune","pluie laminaire","aéré","brumisé","pulsé/massage","concentré/puissant","multi-jets"] },
      { key: "DebitEnSortieDuPommeauBis", label: "Débit en sortie du pommeau", kind: "number", row: 55, unit: "L/min" },
      { key: "PresenceDUnReducteurDe", label: "Présence d'un réducteur de débit", kind: "boolean", row: 55 },
      { key: "BaignoireIndiquerSesDimensions", label: "Baignoire - Indiquer ses dimensions", kind: "number", row: 58, unit: "cm" },
      { key: "Ou", label: "ou", kind: "text", row: 58 },
      { key: "BaignoireIndiquerSonVolume", label: "Baignoire - Indiquer son volume", kind: "number", row: 58, unit: "L" },
      { key: "TemperatureMaxEcsBis", label: "Température max ECS", kind: "number", row: 61, unit: "°C" },
      { key: "TempsDObtentionBis", label: "Temps d'obtention", kind: "number", row: 61, unit: "s" },
      { key: "NumeroReseauEcsDAppartenanceBis", label: "Numéro réseau ECS d'appartenance", kind: "entity-ref", row: 61, refTo: "reseaux_eau_chaude_sanitaire" },
      { key: "EtatGeneralBis", label: "Etat général*", kind: "select", row: 64, options: ["Bon","Moyen","Mauvais"] },
      { key: "DateDerniereMaintenanceBis", label: "Date dernière maintenance", kind: "text", row: 64 },
      { key: "DysfonctionnementsObservesBis", label: "Dysfonctionnements observés", kind: "textarea", row: 67, wide: true },
      { key: "RemarquesBis", label: "Remarques", kind: "textarea", row: 70, wide: true },
      { key: "MauvaisEtatBis", label: "Mauvais état", kind: "text", row: 75 },
      { key: "EquipementAncienFuitePermanenteEntartrageBis", label: "équipement ancien, fuite permanente, entartrage important, flexible abîmé, jets irréguliers en permanence, mauvais état des joints du receveur", kind: "text", row: 75 },
      { key: "Type", label: "Type", kind: "select", row: 77, options: ["Simple EF","Simple ECS","Mélangeur","Mitigeur classique","Mitigeur thermostatique"] },
      { key: "Particularite", label: "Particularité", kind: "text", row: 77 },
      { key: "Temporisation", label: "Temporisation", kind: "select", row: 80, options: L.TEMPORISATION },
      { key: "TempsDeLaTemporisation", label: "Temps de la temporisation", kind: "number", row: 80, unit: "s" },
      { key: "InformationsSurLeBecDu", label: "Informations sur le bec du robinet de la baignoire", kind: "text", row: 83 },
      { key: "DebitEnSortieDuRobinet", label: "Débit en sortie du robinet de la baignoire", kind: "number", row: 86, unit: "L/min" },
      { key: "PresenceDUnLimiteurDeBis", label: "Présence d'un limiteur de débit", kind: "boolean", row: 86 },
      { key: "DiametreNominalDeLAlimentation", label: "Diamètre Nominal de l'alimentation", kind: "number", row: 89, unit: "mm" },
      { key: "MateriauDuTuyauDAlimentation", label: "Matériau du tuyau d'alimentation", kind: "select", row: 89, options: L.MATERIAU_TUYAU },
      { key: "EtatGeneralBisBis", label: "Etat général*", kind: "select", row: 92, options: ["Bon","Moyen","Mauvais"] },
      { key: "DateDerniereMaintenanceBisBis", label: "Date dernière maintenance", kind: "text", row: 92 },
      { key: "DysfonctionnementsObservesBisBis", label: "Dysfonctionnements observés", kind: "textarea", row: 95, wide: true },
      { key: "RemarquesBisBis", label: "Remarques", kind: "textarea", row: 98, wide: true },
      { key: "RemarquesGenerales", label: "Remarques générales", kind: "textarea", row: 105, wide: true },
    ],
  },
  {
    key: "wc",
    route: "wc",
    singular: "WC",
    plural: "WC",
    listColumns: ["Numero","TypeDeToiletteOuUrinoir","Emplacement","NombreDEquipementsIdentiques"],
    fields: [
      { key: "TypeDePose", label: "Type de pose", kind: "select", row: 7, options: ["suspendu","sur pied"] },
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 7 },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 10 },
      { key: "TypeDeToiletteOuUrinoir", label: "Type de toilette ou urinoir", kind: "text", row: 14 },
      { key: "ReferenceDuModeleSiConnu", label: "Référence du modèle si connu", kind: "text", row: 14 },
      { key: "TypeDAssise", label: "Type d'assise", kind: "select", row: 17, options: ["Adulte non PMR","PMR","Enfants"] },
      { key: "Utilisateurs", label: "Utilisateurs", kind: "select", row: 17, options: ["(plusieurs réponses possibles)","Public extérieur","Personnel","Autres adultes","Enfants","Adolescents","Personnes âgées","PMR"] },
      { key: "AnneeDInstallation", label: "Année d'installation", kind: "number", row: 20 },
      { key: "NombreDEquipementsIdentiques", label: "Nombre d'équipements identiques", kind: "number", row: 20 },
      { key: "DateDernierReglageChasseD", label: "Date dernier réglage chasse d'eau", kind: "text", row: 23 },
      { key: "TypeDeReservoirDeChasse", label: "Type de réservoir de chasse", kind: "text", row: 23 },
      { key: "VolumeChasse", label: "Volume chasse", kind: "select", row: 26, options: ["<3","2/4","3/6","6/9","6","9",">9","Inconnu","Non concerné"] },
      { key: "VolumeChasseEstimeOuConnu", label: "Volume chasse estimé ou connu", kind: "select", row: 26, options: ["Connu","Estimé","Non connu/non estimé","Non concerné"] },
      { key: "CommandeDeLaChasse", label: "Commande de la chasse", kind: "select", row: 29, options: L.COMMANDE_CHASSE },
      { key: "TemporisationDeLEcoulement", label: "Temporisation de l'écoulement", kind: "select", row: 29, options: L.TEMPORISATION_ECOULEMENT },
      { key: "DureeDeLEcoulementOu", label: "Durée de l'écoulement(s) ou remplissage chasse", kind: "number", row: 32, unit: "s" },
      { key: "NombreDEquipementIdentique", label: "Nombre d'équipement identique", kind: "number", row: 32 },
      { key: "OrigineDeLEau", label: "Origine de l'eau", kind: "select", row: 35, options: ["Eau potable","Eau de pluie","Eau souterraine","Eau grise","écrire toutes les eaux utilisées en cas de possibilité de changement"] },
      { key: "VolumeEauNcDisponible", label: "Volume eau NC disponible", kind: "number", row: 35, unit: "L" },
      { key: "Ventilation", label: "Ventilation ?", kind: "select", row: 38, options: ["pas de ventilation","en continu","intermittente","à détection","indépendante du reste du bâtiment"] },
      { key: "TestDeLaFeuilleDe", label: "Test de la feuille de papier sur la bouche d'extraction", kind: "select", row: 41, options: ["Feuille aspirée","Feuille repoussée","Rien ne se passe"] },
      { key: "EtatVisuelGeneralDesSanitaires", label: "Etat visuel général des sanitaires", kind: "text", row: 41 },
      { key: "Dysfonctionnements", label: "Dysfonctionnements", kind: "select", row: 44, options: ["Fuite de la chasse","Bouton chasse cassé ou bloqué","Bruits de la chasse en continu","Entartrage","Odeurs","WC bouché"] },
      { key: "DisponibiliteDUnLocalA", label: "Disponibilité d'un local à proximité", kind: "select", row: 44, options: ["non","oui à côté","derrière un des murs","oui à l'aplomb aux étages inférieurs"] },
      { key: "LaMajoriteDesToilettesSont", label: "La majorité des toilettes sont-elles positionnées les unes au-dessus des autres dans le bâtiment ?", kind: "text", row: 47 },
      { key: "EstCeQueCertainesToilettes", label: "Est-ce que certaines toilettes ont un mur qui donne sur l'extérieur ?", kind: "text", row: 47 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 50, wide: true },
    ],
  },
  {
    key: "appareils_lavage",
    route: "appareils-lavage",
    singular: "Appareil de lavage",
    plural: "Appareils de lavage",
    listColumns: ["Numero","Emplacement","Type"],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 7 },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 10 },
      { key: "Type", label: "Type", kind: "select", row: 14, options: ["lave linge","lave vaisselle","autolaveuse","lavage du sol manuel"] },
      { key: "Marque", label: "Marque", kind: "text", row: 18 },
      { key: "Modele", label: "Modèle", kind: "text", row: 18 },
      { key: "Utilisations", label: "Utilisations", kind: "select", row: 18, options: ["domestique","collectif","professionnel"] },
      { key: "DateDInstallation", label: "Date d'installation", kind: "text", row: 21 },
      { key: "Capacite", label: "Capacité", kind: "number", row: 21, unit: "kg" },
      { key: "ClasseEnergetique", label: "Classe énergétique", kind: "select", row: 21, options: ["A","B","C","D","E","F","G"] },
      { key: "ListerLesProgrammesLesPlus", label: "Lister les programmes les plus utilisés", kind: "text", row: 24 },
      { key: "TypeDeTextiles", label: "Type de textiles", kind: "select", row: 24, options: ["à cocher (plusieurs réponses possibles) :","vêtements quotidien mixte (coton, mélange, soie, laine, synthétique)","vêtements de sport (synthétique)","vêtements laine","textile hébergement (literie, peignoirs, serviette)","textile ameublement (rideaux, housse)","textile de restauration (nappes, torchons, serviettes de table)","textile médical (tenues, draps)","textile de nettoyage (franges, chiffons, microfibres)","vêtements professionnels très sales","textiles à risques infectieux"] },
      { key: "TypeDAlimentationEnEau", label: "Type d'alimentation en eau", kind: "select", row: 27, options: ["EF seul","EF + ECS","Eau de pluie"] },
      { key: "NbDUtilisationSemaine", label: "Nb d'utilisation / semaine", kind: "number", row: 27 },
      { key: "TemperatureDeLavageLaPlus", label: "Température de lavage la plus fréquente", kind: "text", row: 27 },
      { key: "TauxDeRemplissage", label: "Taux de remplissage", kind: "select", row: 30, options: ["peu rempli","semi-rempli","plein"] },
      { key: "EtatVisuelDeLaMachine", label: "Etat visuel de la machine*", kind: "text", row: 30 },
      { key: "DysfonctionnementsObserves", label: "Dysfonctionnements observés", kind: "textarea", row: 30, wide: true },
      { key: "ProceduresDEntretienRealisees", label: "Procédures d'entretien réalisées", kind: "text", row: 33 },
      { key: "Frequence", label: "Fréquence", kind: "text", row: 33 },
      { key: "NombreDEquipementIdentique", label: "Nombre d'équipement identique", kind: "number", row: 33 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 36, wide: true },
      { key: "MarqueBis", label: "Marque", kind: "text", row: 43 },
      { key: "ModeleBis", label: "Modèle", kind: "text", row: 43 },
      { key: "UtilisationsBis", label: "Utilisations", kind: "select", row: 43, options: ["domestique","collectif","professionnel"] },
      { key: "DateDInstallationBis", label: "Date d'installation", kind: "text", row: 46 },
      { key: "CapaciteBis", label: "Capacité", kind: "text", row: 46 },
      { key: "ClasseEnergetiqueBis", label: "Classe énergétique", kind: "text", row: 46 },
      { key: "TypeDeChargement", label: "Type de chargement", kind: "select", row: 49, options: ["frontal","à capot","à avancement automatique","à convoyeur/tunnel"] },
      { key: "TypeDAlimentationEnEauBis", label: "Type d'alimentation en eau", kind: "select", row: 49, options: ["EF seul","ECS seul","EF + ECS"] },
      { key: "NbDUtilisationSemaineBis", label: "Nb d'utilisation / semaine", kind: "number", row: 49 },
      { key: "ListerLesProgrammesLesPlusBis", label: "Lister les programmes les plus utilisés", kind: "text", row: 53 },
      { key: "TauxDeRemplissageBis", label: "Taux de remplissage", kind: "text", row: 56 },
      { key: "EtatVisuelDeLaMachineBis", label: "Etat visuel de la machine*", kind: "text", row: 56 },
      { key: "TemperatureDeLavageLaPlusBis", label: "Température de lavage la plus fréquente", kind: "text", row: 56 },
      { key: "ProceduresDEntretienRealiseesEt", label: "Procédures d'entretien réalisées (lavage à vide à 65°C, vinaigre blanc, etc.) et fréquence", kind: "text", row: 59 },
      { key: "DysfonctionnementsObservesBis", label: "Dysfonctionnements observés", kind: "textarea", row: 59, wide: true },
      { key: "RemarquesBis", label: "Remarques", kind: "textarea", row: 62, wide: true },
      { key: "NombreDEquipementIdentiqueBis", label: "Nombre d'équipement identique", kind: "number", row: 62 },
      { key: "MarqueBisBis", label: "Marque", kind: "text", row: 69 },
      { key: "ModeleBisBis", label: "Modèle", kind: "text", row: 69 },
      { key: "UtilisationsBisBis", label: "Utilisations", kind: "select", row: 69, options: ["nettoyage ponctuel","nettoyage régulier","nettoyage quotidien"] },
      { key: "DateDInstallationBisBis", label: "Date d'installation", kind: "text", row: 72 },
      { key: "TypeDAutolaveuse", label: "Type d'autolaveuse", kind: "select", row: 72, options: ["autotractée","autoportée","industrielle"] },
      { key: "LargeurDeTravail", label: "Largeur de travail", kind: "text", row: 72 },
      { key: "TypeDAlimentationElectrique", label: "Type d'alimentation électrique", kind: "select", row: 75, options: ["sur batterie","câble d'alimentation"] },
      { key: "TypeDeBrosses", label: "Type de brosses", kind: "select", row: 75, options: ["disque","rouleau","autre"] },
      { key: "TemperatureDeLavageLaPlusBisBis", label: "Température de lavage la plus fréquente", kind: "text", row: 75 },
      { key: "ReglageLePlusUtiliseSur", label: "Réglage le plus utilisé sur le débit d'eau", kind: "text", row: 78 },
      { key: "DosageEtNomDuDetergent", label: "Dosage et nom du détergent utilisé", kind: "text", row: 81 },
      { key: "VolumeReservoirEauPropre", label: "Volume réservoir eau propre", kind: "number", row: 84, unit: "L" },
      { key: "VolumeReservoirEauSale", label: "Volume réservoir eau sale", kind: "number", row: 84, unit: "L" },
      { key: "NbDeRemplissageDuReservoir", label: "Nb de remplissage du réservoir eau propre à chaque utilisation", kind: "number", row: 84 },
      { key: "SurfaceNettoyeeParUtilisation", label: "Surface nettoyée (m²) par utilisation", kind: "number", row: 87, unit: "m²" },
      { key: "NbDUtilisationSemaineBisBis", label: "Nb d'utilisation / semaine", kind: "number", row: 87 },
      { key: "PersonnelForme", label: "Personnel formé", kind: "select", row: 87, options: ["Oui","Non"] },
      { key: "NumeroDuRobinetUtilisePour", label: "Numéro du robinet utilisé pour le remplissage", kind: "text", row: 90 },
      { key: "LieuDeVidangeDesEaux", label: "Lieu de vidange des eaux sales", kind: "text", row: 90 },
      { key: "EtatVisuelDeLaMachineBisBis", label: "Etat visuel de la machine", kind: "text", row: 90 },
      { key: "TypeDeZoneLavee", label: "Type de zone lavée", kind: "text", row: 93 },
      { key: "TypeDeSalissuresRetrouveesDans", label: "Type de salissures retrouvées dans cette zone (sèches, grasses, humides, biologiques, lourdes (huile, boue))", kind: "text", row: 93 },
      { key: "ExigenceDePropreteDeLa", label: "Exigence de propreté de la zone", kind: "text", row: 93 },
      { key: "ProceduresDEntretienDeLa", label: "Procédures d'entretien de la machine et fréquence", kind: "text", row: 97 },
      { key: "DysfonctionnementsObservesBisBis", label: "Dysfonctionnements observés", kind: "textarea", row: 97, wide: true },
      { key: "RemarquesBisBis", label: "Remarques", kind: "textarea", row: 100, wide: true },
      { key: "TypeDeSurface", label: "Type de surface", kind: "select", row: 107, options: ["carrelage (grès, faïence)","pierre (marbre, granit, travertin)","résine époxy / polyuréthane","béton ciré","béton brut","parquet massif","parquet contrecollé","bois stratifié","Linoléum","PVC / vinyle","Moquette en rouleau","dalles de moquette","autre"] },
      { key: "SurfaceNettoyeeParUtilisationBis", label: "Surface nettoyée (m²) par utilisation", kind: "number", row: 107, unit: "m²" },
      { key: "TypeDeMaterielDeLavage", label: "Type de matériel de lavage", kind: "select", row: 107, options: ["balai serpillère à franges (ou balai espagnol)","balai à plat classique","balai à plat avec microfibres pré-imprégnées","balai à plat avec microfibre jetables","balai brosse","balai avec réservoir (spray mop)","Nettoyeur haute-pression (Karcher)","balais à vapeur","Nettoyage au jet","autre"] },
      { key: "ListerLesEquipementsAssociesAu", label: "Lister les équipements associés au matériel de lavage", kind: "text", row: 110 },
      { key: "ListerLeNomDuDetergent", label: "Lister le nom du détergent utilisé et son dosage", kind: "text", row: 113 },
      { key: "TypeDeZoneLaveeBis", label: "Type de zone lavée", kind: "text", row: 116 },
      { key: "TypeDeSalissuresRetrouveesDansBis", label: "Type de salissures retrouvées dans cette zone (sèches, grasses, humides, biologiques, lourdes (huile, boue))", kind: "text", row: 116 },
      { key: "ExigenceDePropreteDeLaBis", label: "Exigence de propreté de la zone", kind: "text", row: 116 },
      { key: "VolumeDesSeauxUtilises", label: "Volume des seaux utilisés", kind: "number", row: 119, unit: "L" },
      { key: "NbDeSeauxUtilisesA", label: "Nb de seaux utilisés à chaque lavage", kind: "number", row: 119 },
      { key: "NbDeLavageParSemaine", label: "Nb de lavage par semaine", kind: "number", row: 119 },
      { key: "RincageDuSol", label: "Rinçage du sol", kind: "select", row: 122, options: ["pas de rinçage","rinçage systématique","rinçage ponctuel"] },
      { key: "UnProtocoleDeLavageEcrit", label: "Un protocole de lavage écrit est communiqué au salarié ?", kind: "select", row: 122, options: ["Oui","Non"] },
      { key: "PersonnelFormeBis", label: "Personnel formé", kind: "select", row: 122, options: ["Oui","Non"] },
      { key: "NumeroDuRobinetUtilisePourBis", label: "Numéro du robinet utilisé pour le remplissage", kind: "text", row: 125 },
      { key: "LieuDeVidangeDesEauxBis", label: "Lieu de vidange des eaux sales", kind: "text", row: 125 },
      { key: "EtatVisuelDesEquipements", label: "Etat visuel des équipements*", kind: "text", row: 125 },
      { key: "ProceduresDeRemplacementDesEquipements", label: "Procédures de remplacement des équipements et d'achat des consommables", kind: "text", row: 128 },
      { key: "DysfonctionnementsObservesBisBisBis", label: "Dysfonctionnements observés", kind: "textarea", row: 128, wide: true },
      { key: "RemarquesBisBisBis", label: "Remarques", kind: "textarea", row: 131, wide: true },
    ],
  },
  {
    key: "structure",
    route: "structure",
    singular: "Structure",
    plural: "Structures",
    listColumns: ["Numero","Emplacement","TypeDeLaStructure"],
    fields: [
      { key: "TypeDeLaStructure", label: "Type de la structure", kind: "select", row: 7, options: ["Structure du bâtiment et réseaux","Espace technique aménageable","Ouvrir la suite en fonction du choix"] },
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 10 },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 13 },
      { key: "TypeDePlanchers", label: "Type de planchers", kind: "select", row: 18, options: ["dalle béton","dalle poutrelle/hourdis","bois","plancher surélevé","dalle structurelle","plots","dalle amovibles","planchers chauffants"] },
      { key: "SiPlancherAvecVideTechnique", label: "Si plancher avec vide technique, hauteur du vide technique", kind: "number", row: 18, unit: "cm" },
      { key: "SiPasDeFauxPlafond", label: "Si pas de faux-plafond, hauteur sous plafond", kind: "number", row: 21, unit: "m" },
      { key: "SiPresenceDUnFaux", label: "Si présence d'un faux-plafond, hauteur disponible dans le plénum", kind: "number", row: 21, unit: "cm" },
      { key: "PresenceDeGainesTechniques", label: "Présence de gaines techniques ?", kind: "select", row: 24, options: ["aucune","horizontales","verticales"] },
      { key: "TypeDeCloisons", label: "Type de cloisons", kind: "select", row: 24, options: ["légère sur ossature (placo)","maçonnée (brique, parpaing, carreau de plâtre)","alvéolaire (prêtes à poser)","techniques (coupe-feu, acoustique renforcé, hydrofuge)","vitrées","démontable/modulaire","bois"] },
      { key: "PresenceDeColonnesDeChute", label: "Présence de colonnes de chute séparées pour les eaux grises ?", kind: "select", row: 27, options: ["oui","non"] },
      { key: "PresenceDUneEvacuationSeparee", label: "Présence d'une évacuation séparée des eaux de lavage, de process et autres ?", kind: "select", row: 27, options: ["Oui","Non"] },
      { key: "PresenceDeTeDeVisite", label: "Présence de Té de visite à intervalles réguliers sur le réseau de collecte", kind: "select", row: 30, options: ["oui","non"] },
      { key: "AccessibiliteDuReseauDeCollecte", label: "Accessibilité du réseau de collecte", kind: "select", row: 30, options: ["Oui","Non"] },
      { key: "SiPasDeTrappesDe", label: "Si pas de trappes de visite pour accéder à un éventuel réseau urine, possible d'en installer ?", kind: "select", row: 33, options: ["oui","non"] },
      { key: "LeReseauDEauPotable", label: "Le réseau d'eau potable actuel passe actuellement dans", kind: "select", row: 33, options: ["des faux-plafonds","des gaines techniques","des vides sanitaires","des trémies","en apparent"] },
      { key: "PossibiliteDInstallerUnReseau", label: "Possibilité d'installer un réseau supplémentaire dans les gaines techniques ?", kind: "text", row: 36 },
      { key: "EstCeQueTousLes", label: "Est-ce que tous les réseaux EU arrivent au même endroit dans le bâtiment ?", kind: "text", row: 36 },
      { key: "EstCeQuIlEst", label: "Est-ce qu'il est possible d'installer une nouvelle ventilation jusqu'au faitage ?", kind: "text", row: 39 },
      { key: "PresenceDUnLocalTechnique", label: "Présence d'un local technique ou sous-sol aménageable ?", kind: "select", row: 44, options: ["oui/non","si oui afficher les questions suivantes"] },
      { key: "UnCamionDeLivraisonDe", label: "Un camion de livraison de cuve et de vidange peut-il se garer à côté de cet espace ?", kind: "select", row: 44, options: ["oui","non"] },
      { key: "SurfaceDisponible", label: "Surface disponible", kind: "number", row: 47, unit: "m²" },
      { key: "LeRoutePermettantDAcceder", label: "Le route (rue + chemin d'accès) permettant d'accéder à cet espace est il accessible pour un camion de livraison ou de vidange (fils électriques, largeur de route, etc.)?", kind: "text", row: 47 },
      { key: "HauteurDisponible", label: "Hauteur disponible", kind: "number", row: 50, unit: "m" },
      { key: "CetEspaceTechniqueEstIl", label: "Cet espace technique est-il accessible aux engins de livraison de cuve et de vidange ?", kind: "select", row: 50, options: ["oui","non"] },
      { key: "CetEspaceEstIlEquipe", label: "Cet espace est-il équipé d'un alimentation électrique ?", kind: "select", row: 53, options: ["oui","non"] },
      { key: "LEspaceEstIlVentile", label: "L'espace est-il ventilé ?", kind: "select", row: 53, options: ["oui","non"] },
      { key: "LeReseau4g5gEst", label: "Le réseau 4G/5G est-il disponible dans cet espace ?", kind: "select", row: 56, options: ["oui","non"] },
      { key: "UnSystemeDeRelevageEst", label: "Un système de relevage est il obligatoire entre la collecte et l'espace de stockage ?", kind: "select", row: 56, options: ["oui","non"] },
      { key: "CetEspaceEstIlEquipeBis", label: "Cet espace est-il équipé d'un siphon de sol pour faciliter le nettoyage (débordements) ?", kind: "select", row: 59, options: ["oui","non"] },
      { key: "UnByPassVersLe", label: "Un by-pass vers le réseau d'eaux usées est-il possible ?", kind: "select", row: 59, options: ["oui","non"] },
      { key: "CetEspaceEstIlProtege", label: "Cet espace est-il protégé du gel ?", kind: "select", row: 62, options: ["oui","non"] },
      { key: "CetEspaceEstIlEquipeBisBis", label: "Cet espace est-il équipé d'un point d'eau potable ?", kind: "select", row: 62, options: ["oui","non"] },
      { key: "LesInterventionsTechniquesDeVidange", label: "Les interventions techniques de vidange des cuves peuvent elles se faire durant les horaires d'ouverture sans perturber le fonctionnement du bâtiment ?", kind: "select", row: 65, options: ["oui","non"] },
      { key: "CetEspaceEstIlOuvert", label: "Cet espace est-il ouvert au public ?", kind: "select", row: 65, options: ["oui","non"] },
      { key: "LeLocalEstIlEloigne", label: "Le local est-il éloigné de la verticale des toilettes présente dans les étages ?", kind: "text", row: 68 },
      { key: "EstIlEnvisageableDInstaller", label: "Est-il envisageable d'installer un dispositif de vidange de la cuve qui ne nécessite pas de pénétrer à l'intérieur du bâtiment ?", kind: "select", row: 68, options: ["oui","non"] },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 73, wide: true },
    ],
  },
  {
    key: "ventilation_batiment",
    route: "ventilation",
    singular: "Ventilation",
    plural: "Ventilation",
    listColumns: ["Numero","SystemeDeVentilation","EmplacementDuSysteme"],
    fields: [
      { key: "SystemeDeVentilation", label: "Système de ventilation", kind: "select", row: 10, options: ["insuflation","ventilation naturelle","VMC simple flux autoréglable","VMC simple flux hygroréglable","VMC double flux","CTA simple flux","CTA double flux","Ne sait pas","Autre"] },
      { key: "EmplacementDuSysteme", label: "Emplacement du système", kind: "text", row: 18 },
      { key: "AnneeDInstallation", label: "Année d'installation", kind: "number", row: 22 },
      { key: "SystemeEnFonctionnementLeJour", label: "Système en fonctionnement le jour de l'audit", kind: "boolean", row: 26 },
      { key: "DegradationsDysfontionnementObserves", label: "Dégradations / dysfontionnement observés", kind: "text", row: 30 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 34, wide: true },
    ],
  },
  {
    key: "incendie",
    route: "incendie",
    singular: "Incendie",
    plural: "Incendie",
    listColumns: ["Numero","Emplacement","PrecisionEmplacement"],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 7 },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 10 },
      { key: "PresenceDeRia", label: "Présence de RIA (Robinets d'Incendie Armés) ?", kind: "select", row: 15, options: ["oui","non"] },
      { key: "PresenceDeSprinkler", label: "Présence de sprinkler ?", kind: "select", row: 15, options: ["Oui","Non"] },
      { key: "PresenceDUnSousCompteur", label: "Présence d'un sous-compteur sur le réseau incendie ?", kind: "select", row: 18, options: ["oui","non"] },
      { key: "PresenceDUneReservieIncendie", label: "Présence d'une réservie incendie ?", kind: "select", row: 18, options: ["Oui","Non"] },
      { key: "VolumeReserveIncendie", label: "Volume réserve incendie", kind: "number", row: 21, unit: "m3" },
      { key: "TypeDEauReserveIncendie", label: "Type d'eau réserve incendie", kind: "select", row: 21, options: ["eau potable","eau de pluie","eau pluviale"] },
      { key: "TestsReglementairesRealisesSurLe", label: "Tests réglémentaires réalisés (essais RIA, essais sprinklers, essais pompes) sur le système incendie :", kind: "text", row: 24 },
      { key: "FrequenceDesTests", label: "Fréquence des tests", kind: "select", row: 24, options: ["hebdomadaire","mensuelle","semestriel","annuelle"] },
      { key: "DureeOuvertureEauDurantLes", label: "Durée ouverture eau durant les tests", kind: "number", row: 27 },
      { key: "VolumeDEauEstimeUtilise", label: "Volume d'eau estimé utilisé par test", kind: "number", row: 27, unit: "L" },
      { key: "PresenceDePurgesReguliersDu", label: "Présence de purges régulièrs du réseau incendie?", kind: "select", row: 30, options: ["Oui","Non"] },
      { key: "FrequenceDesPurges", label: "Fréquence des purges", kind: "select", row: 30, options: ["hebdomadaire","mensuelle","semestrielle","biannuelle","annuelle"] },
      { key: "VolumeDEauEstimePar", label: "Volume d'eau estimé par purge", kind: "number", row: 33, unit: "L" },
      { key: "DestinationDesEauxDeTests", label: "Destination des eaux de tests/purges", kind: "select", row: 33, options: ["rejet au réseau d'assainissement","rejet au réseau pluvial","infiltration à la parcelle"] },
      { key: "PresenceDUnCarnetDe", label: "Présence d'un carnet de suivi des tests/purges ?", kind: "select", row: 36, options: ["Oui","Non"] },
      { key: "PersonneEnChargeDesTests", label: "Personne en charge des tests/purges", kind: "text", row: 36 },
      { key: "DysfonctionnementsObserves", label: "Dysfonctionnements observés", kind: "textarea", row: 39, wide: true },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 42, wide: true },
    ],
  },
  {
    key: "toitures",
    route: "toitures",
    singular: "Toiture",
    plural: "Toitures",
    listColumns: ["Numero","Emplacement","SurfaceDeToiture","ToitureAccessible"],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 7 },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 10 },
      { key: "ToitureAccessible", label: "Toiture accessible ?", kind: "select", row: 15, options: ["Oui","Non"] },
      { key: "TypeDeToiture", label: "Type de toiture", kind: "select", row: 15, options: ["terrasse","pente","multiple pans"] },
      { key: "SurfaceDeToiture", label: "Surface de toiture", kind: "number", row: 15, unit: "m²" },
      { key: "MateriauxDeCouverture", label: "Matériaux de couverture", kind: "select", row: 18, options: ["tuiles terre cuite","ardoises","bac acier","zinc","aluminium","membrane bitumineuse","PVC/EPDM","fibrociment"] },
      { key: "PenteDeToiture", label: "Pente de toiture", kind: "text", row: 18 },
      { key: "NombreDePansDeToiture", label: "Nombre de pans de toiture", kind: "number", row: 18 },
      { key: "PresenceDObstacles", label: "Présence d'obstacles", kind: "text", row: 21 },
      { key: "SiFibrocimentPresenceDAmiante", label: "Si fibrociment, présence d'amiante ?", kind: "boolean", row: 24 },
      { key: "PresenceDePlombOuMetaux", label: "Présence de plomb ou métaux lourds", kind: "select", row: 24, options: ["Oui","Non"] },
      { key: "PresenceDeTraitement", label: "Présence de traitement", kind: "select", row: 24, options: ["oui","non"] },
      { key: "EtatDeLaToiture", label: "Etat de la toiture", kind: "text", row: 27 },
      { key: "ArbresAProximitePouvantApporter", label: "Arbres à proximité pouvant apporter des feuilles ?", kind: "select", row: 30, options: ["Oui","Non"] },
      { key: "SourcesDePollutionAProximite", label: "Sources de pollution à proximité", kind: "select", row: 30, options: ["oui","non"] },
      { key: "TypeDeGouttieres", label: "Type de gouttières", kind: "select", row: 34, options: ["pendante","nantaise","havraise","anglaise"] },
      { key: "TypeDeCheneau", label: "Type de cheneau", kind: "select", row: 34, options: ["encaissé","posé","rampant","noue"] },
      { key: "Materiau", label: "Matériau", kind: "select", row: 34, options: ["PVC","Zinc","aluminium","acier galvanisé","fonte","cuivre"] },
      { key: "EtatDesGouttieres", label: "Etat des gouttières", kind: "text", row: 37 },
      { key: "LargeurDesGouttieres", label: "Largeur des gouttieres", kind: "number", row: 40, unit: "cm" },
      { key: "AccessibiliteDesGouttieresPourEntretien", label: "Accessibilité des gouttières pour entretien", kind: "select", row: 40, options: ["oui","non"] },
      { key: "TypeDeDescentes", label: "Type de descentes", kind: "select", row: 44, options: ["apparente (façade)","encastrée (mur ou gaine technique)"] },
      { key: "NombreDeDescentes", label: "Nombre de descentes", kind: "number", row: 44 },
      { key: "MateriauBis", label: "Matériau", kind: "select", row: 44, options: ["PVC","Zinc","aluminium","acier galvanisé","fonte","cuivre"] },
      { key: "EtatDesDescentes", label: "Etat des descentes", kind: "text", row: 47 },
      { key: "HauteurDesDescentes", label: "Hauteur des descentes", kind: "number", row: 50, unit: "m" },
      { key: "DiametreDesDescentes", label: "Diamètre des descentes", kind: "number", row: 50, unit: "m" },
      { key: "PresenceDeRegardsAccessiblesEn", label: "Présence de regards accessibles en pied de descente", kind: "select", row: 54, options: ["Oui","Non"] },
      { key: "PresenceDAvaloirsEnPied", label: "Présence d'avaloirs en pied de descente", kind: "select", row: 54, options: ["Oui","Non"] },
      { key: "LesEvacuationsDesDescentesSe", label: "Les évacuations des descentes se regoupent-elles en un seul point ?", kind: "select", row: 57, options: ["Oui","Non"] },
      { key: "PresenceDUneGrilleOu", label: "Présence d'une grille ou crapaudine sur les gouttières", kind: "select", row: 57, options: ["Oui","Non"] },
      { key: "DispositifDePretraitementExistant", label: "Dispositif de prétraitement existant", kind: "select", row: 60, options: ["aucun","séparateur premières pluies","filtre sur descente","filtre au sein d'un regard"] },
      { key: "SiDispositifDePretraitementNoter", label: "Si dispositif de prétraitement, noter le modèle et la maille de filtration", kind: "text", row: 60 },
      { key: "EvacuationActuelleDesEauxDe", label: "Evacuation actuelle des eaux de pluie", kind: "select", row: 63, options: ["réseau séparatif pluvial","réseau unitaire","rejet en surface","rejet dans un fossé","noue d'infiltration","puits d'infiltrtion","bassin","autre"] },
      { key: "ContraintesReglementairesLocales", label: "Contraintes réglementaires locales (monuments, PLU,etc.) ?", kind: "text", row: 63 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 66, wide: true },
    ],
  },
  {
    key: "piscines",
    route: "piscines",
    singular: "Bassin",
    plural: "Piscines",
    listColumns: ["Numero","Nom","Emplacement","VolumeDuBassin"],
    fields: [
      { key: "Nom", label: "Nom", kind: "text", row: 7 },
      { key: "Emplacement", label: "Emplacement", kind: "select", row: 7, options: ["Intérieure","Extérieure","Extérieure avec possibilté d'être couverte"] },
      { key: "PourLesPiscinesIndividuellesFaut", label: "pour les piscines individuelles, faut-il ajouter la période d'utilisation de la piscine dans l'année ?", kind: "text", row: 7 },
      { key: "PrecisionEmplacementEtUtilisation", label: "Précision emplacement et utilisation", kind: "text", row: 10 },
      { key: "Type", label: "Type", kind: "select", row: 13, options: ["Enterré","Semi-enterrée","Hors sol avec structure","Hors sol tubulaire","Hors sol autoportée"] },
      { key: "AnneeDeConstruction", label: "Année de construction", kind: "number", row: 13 },
      { key: "MateriauxDeConstruction", label: "Matériaux de construction", kind: "text", row: 13 },
      { key: "MateriauxDeRevetement", label: "Matériaux de revêtement", kind: "select", row: 13, options: ["Carrelage","Résine","Liner","Coque","Plaques aluminium"] },
      { key: "TypeDeCouverture", label: "Type de couverture", kind: "select", row: 16, options: ["bâches à bulles (été)","bâche d'hivernage","couverture à barres (4saisons)","volet roulant automatique","volet roulant manuel","abri","terrasse mobile","autre précisé dans remarques"] },
      { key: "AnneeDerniereRenovation", label: "Année dernière rénovation", kind: "number", row: 16 },
      { key: "TravauxEffectues", label: "Travaux effectués", kind: "text", row: 16 },
      { key: "PresenceConnueDeFuites", label: "Présence connue de fuites", kind: "boolean", row: 19 },
      { key: "VolumeEstimeDesFuitesAn", label: "Volume estimé des fuites/an", kind: "number", row: 19 },
      { key: "Dysfonctionnements", label: "Dysfonctionnements", kind: "textarea", row: 19, wide: true },
      { key: "EtatGeneral", label: "Etat général*", kind: "select", row: 22, options: ["Bon","Moyen","Mauvais"] },
      { key: "VolumeDuBassin", label: "Volume du bassin", kind: "number", row: 22, unit: "m3" },
      { key: "NbDeJourDOuverture", label: "Nb de jour d'ouverture /an", kind: "number", row: 22 },
      { key: "FrequentationJournaliere", label: "Fréquentation journalière", kind: "number", row: 22 },
      { key: "ConsigneApportQuotidienBaigneur", label: "Consigne apport quotidien / baigneur", kind: "number", row: 25, unit: "L" },
      { key: "VolumeDApportQuotidien", label: "Volume d'apport quotidien", kind: "number", row: 25, unit: "L" },
      { key: "ModeDeRemplissageDuBassin", label: "Mode de remplissage du bassin", kind: "select", row: 25, options: ["manuel","automatique avec flotteur"] },
      { key: "OrigineEauDuBassin", label: "Origine eau du bassin", kind: "select", row: 28, options: ["eau potable","eau de mer","eau souterraine","eau de pluie","eau pluviale","eau de surface"] },
      { key: "TemperatureDeConsigneDuBassin", label: "Température de consigne du bassin", kind: "number", row: 28, unit: "°C" },
      { key: "DesinfectionDeLEau", label: "Désinfection de l'eau", kind: "text", row: 31 },
      { key: "TraitementsAutomatise", label: "Traitements automatisé", kind: "boolean", row: 31 },
      { key: "TypeDeFiltration", label: "Type de filtration", kind: "text", row: 31 },
      { key: "NbDeLavageDeFiltre", label: "Nb de lavage de filtre / mois", kind: "number", row: 34 },
      { key: "VolumeRejeteMois", label: "Volume rejeté / mois", kind: "number", row: 34, unit: "m3" },
      { key: "NbDeVidangeAn", label: "Nb de vidange/an", kind: "number", row: 34 },
      { key: "VolumeRejeteAn", label: "Volume rejeté / an", kind: "number", row: 34, unit: "m3" },
      { key: "PossibiliteDeCreerUneZone", label: "Possibilité de créer une zone de stockage des eaux rejetées", kind: "boolean", row: 37 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 40, wide: true },
    ],
  },
  {
    key: "espace_vert_exterieur",
    route: "espaces-exterieurs",
    singular: "Espace extérieur",
    plural: "Espaces extérieurs",
    listColumns: ["Numero","Emplacement"],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 7 },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 10 },
      { key: "SurfaceDeCetteParcelle", label: "Surface de cette parcelle", kind: "number", row: 14, unit: "m2" },
      { key: "DontSurfaceImpermeable", label: "Dont surface imperméable", kind: "number", row: 14, unit: "m2" },
      { key: "TypeDeGestionDesEaux", label: "Type de gestion des eaux pluviales", kind: "select", row: 14, options: ["aucune (ruissellement libre)","infiltration à la parcelle directe","stockage + infiltraion à la parcelle","stockage + réutilisation","rejet au réseau pluvial enterré","rejet au réseau unitaire enterré","rejet vers le milieu superficiel (fossé, cours d'eau)"] },
      { key: "PossibiliteDeRedirigerCesEaux", label: "Possibilité de rediriger ces eaux pour infiltration sur la parcelle", kind: "boolean", row: 21 },
      { key: "Precision", label: "Précision", kind: "textarea", row: 21, wide: true },
      { key: "PossibiliteDeRedirigerCesEauxBis", label: "Possibilité de rediriger ces eaux pour stockage sur la parcelle", kind: "boolean", row: 24 },
      { key: "PrecisionBis", label: "Précision", kind: "textarea", row: 24, wide: true },
      { key: "SurfaceArrosee", label: "Surface arrosée", kind: "number", row: 28, unit: "m2" },
      { key: "TypeDeSurfaceAArroser", label: "type de surface à arroser", kind: "text", row: 28 },
      { key: "PrecisionsDesVegetauxSurCette", label: "Précisions des végétaux sur cette surface", kind: "text", row: 31 },
      { key: "ExpositionDeLaParcelle", label: "Exposition de la parcelle", kind: "select", row: 34, options: ["Ensoleillée","Ombragée","Mi-ombragée"] },
      { key: "PenteDeLaParcelle", label: "Pente de la parcelle", kind: "select", row: 34, options: ["nulle","faible","moyenne","forte"] },
      { key: "PresenceDePaillage", label: "Présence de paillage", kind: "boolean", row: 34 },
      { key: "ModeDArrosage", label: "Mode d'arrosage", kind: "select", row: 37, options: ["Tuyau manuel","Arrosoir","Oyas","Micro asperseur","Arrosage goutte à goutte","Arrosage tuyaux poreux","Tuyères","Arrosage non sélectif","Autre"] },
      { key: "PilotageDeLArrosage", label: "Pilotage de l'arrosage", kind: "select", row: 37, options: ["Manuel","En fonction de la météo","Horloge","Sonde humidité","Connecté"] },
      { key: "Precisions", label: "Précisions", kind: "textarea", row: 37, wide: true },
      { key: "SignesDeSurarrosage", label: "Signes de surarrosage", kind: "select", row: 40, options: ["aucun","ruissellement","flaques","mousse","sol détrempé"] },
      { key: "SignesDeSousArrosage", label: "Signes de sous-arrosage", kind: "select", row: 40, options: ["aucun","végétaux stressés","zones sèches","jaunissement"] },
      { key: "PeriodeDArrosageDansLa", label: "Période d'arrosage dans la journée", kind: "select", row: 40, options: ["Matin","Soir","En pleine journée"] },
      { key: "OrigineEauPourLArrosage", label: "Origine eau pour l'arrosage", kind: "select", row: 43, options: ["eau potable","eau de pluie","eau pluviale","eau grise","eau souterraine"] },
      { key: "CapaciteStockageEauNc", label: "Capacité stockage eau NC", kind: "number", row: 43, unit: "m3" },
      { key: "NcNonConventionnelle", label: "NC = non conventionnelle", kind: "text", row: 43 },
      { key: "NbDeMoisDArrosage", label: "Nb de mois d'arrosage / an", kind: "number", row: 46 },
      { key: "DureeDUnArrosage", label: "Durée d'un arrosage", kind: "number", row: 46 },
      { key: "NbDArrosageMois", label: "Nb d'arrosage / mois", kind: "number", row: 46 },
      { key: "NombreDeRobinetDEau", label: "Nombre de robinet d'eau potable utilisés", kind: "number", row: 49 },
      { key: "NumerosDesRobinetsCorrespondants", label: "Numéros des robinets correspondants", kind: "select", row: 49, options: ["depuis la liste des robinets"] },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 52, wide: true },
      { key: "Utilisation", label: "Utilisation", kind: "text", row: 56 },
      { key: "ModeDeNettoyage", label: "Mode de nettoyage", kind: "select", row: 56, options: L.MODE_NETTOYAGE },
      { key: "MotifDuNettoyage", label: "Motif du nettoyage", kind: "select", row: 56, options: ["esthétique","hygiène","sécurité","entretien","autre"] },
      { key: "PrecisionsBis", label: "Précisions", kind: "textarea", row: 59, wide: true },
      { key: "OrigineEauPourLeNettoyage", label: "Origine eau pour le nettoyage", kind: "select", row: 62, options: ["eau potable","eau de pluie","eau pluviale","eau grise","eau souterraine"] },
      { key: "CapaciteStockageEauNcBis", label: "Capacité stockage eau NC", kind: "number", row: 62, unit: "m3" },
      { key: "DureeDUnNettoyage", label: "Durée d'un nettoyage", kind: "number", row: 65 },
      { key: "NbDeNettoyageMois", label: "Nb de nettoyage/mois", kind: "number", row: 65 },
      { key: "NombreDeRobinetDEauBis", label: "Nombre de robinet d'eau potable utilisés", kind: "number", row: 68 },
      { key: "NumerosDesRobinetsCorrespondantsBis", label: "Numéros des robinets correspondants", kind: "select", row: 68, options: ["depuis la liste des robinets"] },
      { key: "RemarquesBis", label: "Remarques", kind: "textarea", row: 71, wide: true },
      { key: "Usage", label: "Usage", kind: "text", row: 75 },
      { key: "PrecisionsBisBis", label: "Précisions", kind: "textarea", row: 75, wide: true },
      { key: "OrigineEau", label: "Origine eau", kind: "select", row: 78, options: ["eau potable","eau de pluie","eau pluviale","eau grise","eau souterraine"] },
      { key: "CapaciteStockageEauNcBisBis", label: "Capacité stockage eau NC", kind: "number", row: 78, unit: "m3" },
      { key: "VolumeDEauUtliseMois", label: "Volume d'eau utlisé / mois", kind: "number", row: 81, unit: "m3" },
      { key: "FrequenceNombreDeMoisAn", label: "Fréquence : nombre de mois / an", kind: "text", row: 81 },
      { key: "NombreDeRobinetDEauBisBis", label: "Nombre de robinet d'eau potable utilisés", kind: "number", row: 84 },
      { key: "NumerosDesRobinetsCorrespondantsBisBis", label: "Numéros des robinets correspondants", kind: "select", row: 84, options: ["depuis la liste des robinets"] },
      { key: "RemarquesGenerales", label: "Remarques générales", kind: "textarea", row: 87, wide: true },
    ],
  },
  {
    key: "opportunites",
    route: "opportunites",
    singular: "Opportunité",
    plural: "Opportunités",
    listColumns: ["Numero","Emplacement"],
    fields: [
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 7 },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 10 },
      { key: "UtilisationsExterieuresPotentielles", label: "Utilisations extérieures potentielles", kind: "select", row: 16, options: ["arrosage","nettoyage surface","nettoyage véhicule","bassin","fontaine","piscine","autre"] },
      { key: "UtilisationsInterieuresPotentielles", label: "Utilisations intérieures potentielles", kind: "select", row: 16, options: ["chasse d'eau","lavage de sol","lavage de linge","process technique","autre"] },
      { key: "AutresUtilisationsInterieuresNonReglementaires", label: "Autres utilisations intérieures non réglementaires", kind: "text", row: 16 },
      { key: "PossibiliteDImplanterUneCuve", label: "Possibilité d'implanter une cuve sur la parcelle ?", kind: "select", row: 19, options: ["Non","Entérée","Aérienne"] },
      { key: "EspaceDisponiblePourUneCuve", label: "Espace disponible pour une cuve en toiture ?", kind: "select", row: 19, options: ["Oui","Non"] },
      { key: "ContraintesDImplantationDUne", label: "Contraintes d'implantation d'une cuve", kind: "text", row: 22 },
      { key: "AccesPossibleAuxEnginsEt", label: "Accès possible aux engins et camion de livraison de cuve", kind: "select", row: 25, options: ["Oui","Non"] },
      { key: "ByPassPossibleDeLa", label: "By-pass possible de la cuve vers une aire d'infiltration ou le réseau pluvial", kind: "select", row: 25, options: ["Oui","Non"] },
      { key: "QuelEstLePotentielTechnique", label: "Quel est le potentiel technique de réutilisation de l'eau de pluie sur ce bâtiment ?", kind: "select", row: 28, options: ["fort","moyen","faible","à aproffondir"] },
      { key: "ListerLesTypesDEaux", label: "Lister les types d'eaux grises présentes dans le bâtiment", kind: "text", row: 33 },
      { key: "CertainsPointsDEauProduisant", label: "Certains points d'eau produisant des eaux grises sont-ils regroupés ? Si oui, lesquels ?", kind: "text", row: 36 },
      { key: "LEvacuationDuLaveLinge", label: "L'évacuation du lave-linge peut elle être dissociée des autres évacuations d'eaux grises ?", kind: "select", row: 36, options: ["Oui","Non"] },
      { key: "ListerLesPrincipauxProduitsChimiques", label: "Lister les principaux produits chimiques utilisés dans le bâtiment qui sont susceptibles de se retrouver dans les eaux ménagères", kind: "text", row: 39 },
      { key: "ListerLesEauxDeLavage", label: "Lister les eaux de lavage produites dans le bâtiment pouvant être réutilisées", kind: "text", row: 42 },
      { key: "UtilisationsExterieuresPotentiellesBis", label: "Utilisations extérieures potentielles", kind: "select", row: 45, options: ["arrosage","nettoyage surface","nettoyage véhicule","bassin","fontaine","autre"] },
      { key: "UtilisationsInterieuresPotentiellesBis", label: "Utilisations intérieures potentielles", kind: "select", row: 45, options: ["chasse d'eau","lavage de sol","process","tours de refroidissement","autre"] },
      { key: "AutresUtilisationsInterieuresNonReglementairesBis", label: "Autres utilisations intérieures non réglementaires", kind: "text", row: 45 },
      { key: "EstCeQueLeBatiment", label: "Est-ce que le bâtiment est innocupé pendant de longue période (>3 semaines) ?", kind: "select", row: 48, options: ["oui","non"] },
      { key: "QuelEstLePotentielTechniqueBis", label: "Quel est le potentiel technique de recyclage des eaux ménagères sur ce bâtiment ?", kind: "select", row: 51, options: ["fort","moyen","faible","à aproffondir"] },
      { key: "CertainsToilettesSontIlsRegroupes", label: "Certains toilettes sont-ils regroupés dans le bâtiment ? Si oui, lesquels ?", kind: "text", row: 56 },
      { key: "ValorisationDesNutrimentsSurPlace", label: "Valorisation des nutriments sur place intéressante (espaces verts, potager, etc.) ?", kind: "select", row: 59, options: ["oui","non"] },
      { key: "APremiereVueQuelEst", label: "A première vue, quel est la taille du gisement urine estimé (nombre d'utilisateurs VS fréquence de passage) ?", kind: "select", row: 59, options: ["faible","moyen","élevé"] },
      { key: "QuelEstLePotentielTechniqueBisBis", label: "Quel est le potentiel technique de collecte des urines dans ce bâtiment ?", kind: "select", row: 62, options: ["fort","moyen","faible","à aproffondir"] },
      { key: "PresenceDUnLieuInteressant", label: "Présence d'un lieu intéressant pour valoriser les nutriments à proximité du bâtiment ?", kind: "select", row: 62, options: ["Oui","Non"] },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 66, wide: true },
    ],
  },
  {
    key: "autre",
    route: "autre",
    singular: "Autre",
    plural: "Autres",
    listColumns: ["Numero","Choix","Nom","Emplacement"],
    fields: [
      { key: "Choix", label: "Choix", kind: "select", row: 7, options: ["ouvrant les champs à la suite en question :","Autre information","Autre utilisation de l'eau"] },
      { key: "Nom", label: "Nom", kind: "text", row: 10 },
      { key: "Emplacement", label: "Emplacement", kind: "text", row: 13 },
      { key: "PrecisionEmplacement", label: "Précision emplacement", kind: "text", row: 16 },
      { key: "Remarques", label: "Remarques", kind: "textarea", row: 55, wide: true },
    ],
  },
];

/** Retrouve une entité par sa clé de stockage. */
export function entityByKey(key: string): EntityDef | undefined {
  return AUDIT_SCHEMA.find((e) => e.key === key);
}

/** Retrouve une entité par son segment d'URL. */
export function entityByRoute(route: string): EntityDef | undefined {
  return AUDIT_SCHEMA.find((e) => e.route === route);
}
